### ISSUE TITLE
Region/Area Permissions

### ISSUE THREAD

**Issue by austin5919** [lucko/LuckPerms#1007]
Is it possible to have permissions set for certain regions, such as the area between 50,50,50 and 100,100,100? I know we are able to set permissions for worlds and was hoping that there is a was for regions/areas too.

**Comment by AlekEagleYT** [comment]
Well, for same world permissions I am not certain but from what I know, no. Though, I can think of some ways to do this, one is to have command block(s) that will determine where the player is and if they need to be in a different group, and if they do need to be in a different group the command block(s) it switch it for them, another is to have warp points around the map that will warp you to a different world with different permissions. That's just my take on it and I hope I helped answer your question.

On May 18, 2018, at 09:52, Austin <notifications@github.com> wrote:

Is it possible to have permissions set for certain regions, such as the area between 50,50,50 and 100,100,100? I know we are able to set permissions for worlds and was hoping that there is a was for regions/areas too.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lucko/LuckPerms","title":"lucko/LuckPerms","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/lucko/LuckPerms">https://github.com/lucko/LuckPerms</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Region/Area Permissions (#1007)"}],"action":{"name":"View Issue","url":"<a href="https://github.com/lucko/LuckPerms/issues/1007">https://github.com/lucko/LuckPerms/issues/1007</a>"}}}{"@type":"MessageCard","@context":"<a href="http://schema.org/extensions">http://schema.org/extensions</a>","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Region/Area Permissions (#1007)","sections":[{"text":"","activityTitle":"**Austin**","activityImage":"<a href="https://avatars2.githubusercontent.com/u/6257786?s=160">https://avatars2.githubusercontent.com/u/6257786?s=160</a>\u0026v=4","activitySubtitle":"@austin5919","facts":[{"name":"Repository: ","value":"lucko/LuckPerms"},{"name":"Issue #: ","value":1007}]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"<a href="https://api.github.com">https://api.github.com</a>","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"lucko/LuckPerms\",\"issueId\":1007,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"<a href="https://api.github.com">https://api.github.com</a>","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"lucko/LuckPerms\",\"issueId\":1007}"},{"targets":[{"os":"default","uri":"<a href="https://github.com/lucko/LuckPerms/issues/1007">https://github.com/lucko/LuckPerms/issues/1007</a>"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"<a href="https://api.github.com">https://api.github.com</a>","body":"{\"commandName\":\"MuteNotification\",\"threadId\":336846374}"}],"themeColor":"26292E"}

**Comment by ktole1999** [comment]
why reinvent the wheel. install a claim mod such as grief prevention. you can disable modules in the mod that are not needed.

**Comment by lucko** [comment]
You can use WorldGuard regions + ExtraContexts

https://github.com/lucko/ExtraContexts
