### ISSUE TITLE
Vault & LuckPerms

### ISSUE THREAD

**Issue by BiGUNMAN** [lucko/LuckPerms#101]
Hi, I use a plugin called MineSync that syncs ranks between the server and Xenforo. It uses Vault to get the ranks, Apparently it has an issue getting ranks from Vault --> LuckPerms.

Here's a pastebin of the error: http://pastebin.com/BvaVAT4z - From my impression LuckPerms supports vault, so I'm personally confused.

**Comment by lucko** [comment]
What is the output of `/vault-info`?

**Comment by BiGUNMAN** [comment]
Good: http://i.imgur.com/JZmonaY.png

**Comment by lucko** [comment]
Not sure. Can you link me to the source/download page of MineSync?

**Comment by LordRobust** [comment]
Hi. Apantic developer here, we make MineSync.

@lucko MineSync is proprietary software. You can read up on it [here](https://www.apantic.com/products/minesync.10/).

This line causes the above error:
`String[] vaultGroups = Main.perms.getPlayerGroups(player);`

https://milkbowl.github.io/VaultAPI/net/milkbowl/vault/permission/Permission.html#getPlayerGroups(org.bukkit.entity.Player)

**Comment by lucko** [comment]
The trace above indicates that you're querying the SuperPerms provider:
`at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91) ~[?:?]`

which is provided by Vault as a fallback.


However, the output of the `/vault-info` command once the server has started indicates that LuckPerms is in-fact registered.

This issue should have been fixed by de09ae94b81d52c41efe3c9971e4e45ed8759d96 and b72e5f5437ff0e93169dc2179b98184c861cdc72.

@BiGUNMAN Are you sure you're using the latest version? Try the newest from here: https://ci.lucko.me/job/LuckPerms/

**Comment by lucko** [comment]
Assuming you were running an old build - feel free to re-open if the issue persists in the latest builds.
