### ISSUE TITLE
The Plugin doesn't work :(

### ISSUE THREAD

**Issue by vascYT** [lucko/LuckPerms#1015]
Hey! I put the LuckPerms Plugin in the plugins Folder and restart the server... Then the Plugin was red when I type '/pl' in the Chat.. Can you help me?

**Comment by smmmadden** [comment]
What server & version, luckperms type and version did you use? 
Did you try using /lp to see if the plugin was properly installed?  
Did you get startup errors when you started the server?  
Can you provide the startup logs showing what was done? (via pastebin or another site link)

Just saying it doesn't work isn't helpful in knowing what it is you see that isn't working since we have visibility into what you did or didn't do. :-)

**Comment by vascYT** [comment]
Yes i try to type /lp but there comes nothing... Server Version: 1.8
I didn't see any errors but i will look in the logs

**Comment by smmmadden** [comment]
what server (minecraft, craftbukkit, bukkit, forge, sponge, spigot, etc.) and if version 1.8 - try using a more recent release like 1.12.2 :-)
Post your startup logs on pastebin or some place so we can see what's going on.
which luckperms are you using - there are 4 of them and what version?

**Comment by lucko** [comment]
Check your console when LP enables - it will tell you what the problem is there, and what you need to do to fix it. :)
