### ISSUE TITLE
Not enough open issues

### ISSUE THREAD

**Issue by Miclebrick** [lucko/LuckPerms#1023]
Out of nearly a thousand issues, there are only ~5 open issues on this repository. This is abnormal and borderline heresy.

**Comment by BrainStone** [comment]
\*poofs this issue away\*  
Magic 😎

**Comment by lucko** [comment]
I don't really understand what you're asking here - if anything at all.

Just to clarify, issues are closed when:

* The bug is fixed
* The question is answered
* The suggestion is implemented, or deemed to be out of scope


so, one of the above is true in most cases, for all of the closed issues on this repository.

**Comment by Miclebrick** [comment]
(It's a joke, I'm just commenting on how this repository has a phenomenal closed to open issue ratio)

**Comment by lucko** [comment]
Oh uh, thanks!

:)
