### ISSUE TITLE
Large memory usage for LPSubscriptionMap

### ISSUE THREAD

**Issue by Scarsz** [lucko/LuckPerms#1041]
Hey there, on our live server (Paper) LuckPerms is using 400MB for a map and it's entries, something related to subscriptions. Is this a normal amount of usage?

![Memory usage](https://scarsz.me/i/tsfkj.png)

**Comment by lucko** [comment]
Uhh no, that doesn't seem normal.

LPSubscriptionMap is just a replacement for a map already in the Bukkit PluginManager instance, with a few changes to make it faster, and work properly with the way LP handles subscriptions.

Soo, most likely another plugin doing something silly.

I've pushed this c0cd197bd0d3f336405f63ae7ceed6d3b6e84c29 change to ensure players can't get added (since LP handles those separately)
