### ISSUE TITLE
Permissions won't take effect

### ISSUE THREAD

**Issue by PsyKiere** [lucko/LuckPerms#1042]
Hello,

First of all, I have to tell you that I am new to this plugin and to this universe.
I have read the wiki, and tried to set it up for the first time today.

I have a spigot minecraft 1.12.2 server with LuckPerms 4.0.18.

I managed to give myself permission to use the plugin : /lp user x permission set luckperms.* true
But I can't figure out why other permissions won't work
(I deopped myself)

I tried : /lp user x permission set essentials.home false
But I was still able to use the command /home

I also tried : /lp user x permission set minecraft.command.xp true
But didn't work either, even though the output indicate that the permission has been set.

Also, I made no change to the config file

Thank you for your concern

**Comment by PsyKiere** [comment]
Ow, I used the latest available on my host's panel, I will upload the latest one manually and get back to you

**Comment by PsyKiere** [comment]
So, I updated, and deleted all old settings for the plugin.
Tried again, but exactly the same happenned.
I changed storage to yaml to have acccess :


name: Pierre
primary-group: default
permissions:
- luckperms.*
- essentials.back:
    value: false
- essentials.back.ondeath:
    value: false
- essentials.home:
    value: false
- minecraft.command.xp
parents:
- default


Only the - luckperms.* works
I tried setting the same permissions to the default group.
I tried also /lp user x permission set essentials.* false
But still have access to it's commands. (unset the permission then)

**Comment by Argetan** [comment]
Are you sure that you de-opped yourself and could it be that you have the `*` permissions perhaps? If so could it be the case that the group `default` gives you access to the Essentials commands?

If this isn't the case then you could try and do `/lp verbose on userName`, you then execute the command you want to check such as `/home`, now that verbose is turned on it will tell you exactly which permissions it checks and whether they returned true or false, this way you can figure out where the fault might be (aka which permission is returning `true` instead of `false). 

Also quick reminder that you can do `/lp group groupName permission list` and `/lp user userName permission list` to get group/user permissions. To get a user's parents/groups do `/lp user userName listgroups`.

P.s. To turn off verbose logging do `/lp verbose off`.

**Comment by PsyKiere** [comment]
Hello,
Thanks Argetan for your answer.
I turned on verbose and managed to set permission true to /xp (by setting it true to essentials.exp.* instead of minecraft.command.xp)
But when I use /back or /home, I get no return from verbose.

**Comment by rjohnson98126** [comment]
can i give you a suggestion?   make at least 2 groups.  preferably 3 or 4 groups.      default is the group that anyone joining will get.  you dont' want every rando have that kind of access.   

"default", give it weight.10
"member" give it weight.20, and that it inherits its parent default
"moderator" give it weight.30, and that it inherits its parent member
"admin" give it weight.30, and that it inherits its parent moderator

default should have no, or very few, permissions.
such as essentials.chat

admin should have all permissions
such as luckperms.*
and essentials.*
and minecraft.command.*
and whatever else youre using.

this will save you so much headache later, and at least get you started on a bare minimum best practices model that you can adjust and expand later.

**Comment by Argetan** [comment]
@PsyKiere when you use /back or /home whilst opped do they work then? If not you might want to update Essentials as I'm starting to think the issue lies there. Also, keep in mind that some Essential commands/features require you to have separate Jars such as Essentials-Spawn-XXX.jar

The latest version of all Essential Jars can be found [here](https://www.spigotmc.org/resources/essentialsx.9089/).

**Comment by PsyKiere** [comment]
Hello,
Thank you Argetan, it finally worked by updating Essentials.
I had 2.0.1 and upgraded to 2.15.0.1
Sorry for the bother, I should have upgraded before.
Thanks

**Comment by Nocrofade** [comment]
Stop using this fucking luckperms . Its broken and annoying as fuck. Switch to permsissionsEx

**Comment by AgentIce** [comment]
> Stop using this fucking luckperms . Its broken and annoying as fuck. Switch to permsissionsEx

Awfully unnecessary comment, issue was closed 2 years ago. Besides, luckperms is not broken. Rage some place else.

**Comment by SixBulb20094036** [comment]
hi im do permiaion and for one time work next time join and write im don't hace acces what me do?
