### ISSUE TITLE
Ranks don't apply after using parent command.

### ISSUE THREAD

**Issue by Wolfeiii** [lucko/LuckPerms#1045]
So I used the parent command to make it easier with the permissions. And now when Im going to change a rank it doesn't change, please help.

**Comment by Andre601** [comment]
More information please.

* What command did you use? (Exact syntax)
* What version of LuckPerms?

**Comment by TheIntelloBox** [comment]
Hi ! :D 

I have the same problem. :D
I'm using V4.2.17 and I used : /lp user RyukaTV parent set comte true 

And it doesn't work. :D

**Comment by merjilin** [comment]
`/lp user RyukaTV parent set comte true` is probably not doing what you expect it to do :P 

That command thinks `true` is the server context, making it appear as it nothing was changed. The `parent add/set` commands do not require `true` or `false` to be appended at the end of the command, as specified on the wiki.

The correct command would be `/lp user RyukaTV parent set comte` which would make the group global. Hope this helps!

**Comment by TheIntelloBox** [comment]
I already did that but it doesn't work.

**Comment by Argetan** [comment]
What does it say when you do `/lp user RyukaTV listgroups`? Could it be that it did add the group but that permissions are overshadowed by another group?

`/lp user RyukaTV parent set comte` would remove all other groups/parents so that the user is only part of the group `comte`. `/lp user RyukaTV parent add comte` will *add* the group `comte` to user whilst also keeping all other parents/groups.

**Comment by TheIntelloBox** [comment]
If I do /lp user RyukaTV parent set comte, it says "rank changed" but the player has the same rank as before.

**Comment by Argetan** [comment]
Are there any messages in the console?

**Comment by TheIntelloBox** [comment]
Nop.

**Comment by lucko** [comment]
Can you give some example screenshots of what you mean?

**Comment by TheIntelloBox** [comment]
That's easy to understand. xD
 
If I do /lp user RyukaTV parent set comte, the rank of RyukaTV doesn't change. :D

**Comment by lucko** [comment]
You said that the output of `/lp user RyukaTV listgroups` doesn't remain the same - therefore their rank is changing.

It sounds like maybe it's just their prefix that isn't being changed? If so, you just need to configure the prefixes for each group properly.

Doesn't seem that there's any LP bug here - I have no reason to believe otherwise and you're not willing to provide screenshots.
