### ISSUE TITLE
Memory leak in bungeecord version

### ISSUE THREAD

**Issue by Sir-Will** [lucko/LuckPerms#1071]
There seems to be a memory leak in the bungeecord version with the contexts of luckperms:

LuckPerms-Bungee-4.2.12

![](https://i.imgur.com/zT3nepd.jpg)
![](https://i.imgur.com/07Md75q.jpg)
![](https://i.imgur.com/f1Ppmz1.jpg)
![](https://i.imgur.com/RUVp2MR.jpg)

This might be an issue in the other versions too but not noticeable because those servers restart frequently while bungeecord servers don't.

**Comment by lucko** [comment]
I think probably related to https://github.com/lucko/LuckPerms/issues/1005

My guess is that it's an issue with the way `#weakKeys` works on the cache - I can tidy this up quite a bit, and also optimise it somewhat on Bungee, since the distributed timeout pattern used on Bukkit/Nukkit/Sponge isn't effective on BungeeCord.

I haven't received any other reports of this happening (other than the one above) - but you're of course right about uptime.

**Comment by lucko** [comment]
Going to assume this was fixed by ^

Please re-open this ticket if that's not the case :)

**Comment by Sir-Will** [comment]
Alright, thanks.
