### ISSUE TITLE
negative permission

### ISSUE THREAD

**Issue by madtomic** [lucko/LuckPerms#1079]
BetterEnderChest can disable the opening of the Ender Chest. Is it possible to give player negative permission in LP to not give player access to Ender Chest like in PEX? In PEX, I can simply add -betterenderchest.user.open and it would do the reverse effect but in LP is hard to figure out.

Any way unsetting the permission node betterenderchest.user.open (which is set by default).

**Comment by BrainStone** [comment]
Instead of `/lp ... permission set <perm>` or `/lp ... permission set <perm> true`, use `/lp ... permission set <perm> false`

Alternatively you can use the web editor. Just click on the green `true` to toggle it false.

Anyways. I’d recommend you reading the wiki. As that explains all of that. The recommended page to start is the Usage page.

**Comment by madtomic** [comment]
Thank you again for helping!
