### ISSUE TITLE
Suggestion: Custom Command

### ISSUE THREAD

**Issue by Morsmorse** [lucko/LuckPerms#1083]
The possibility to change the command to use the LuckPerms commands would be useful.
So that when a different command is configured `/lp user username info` doesn't work anymore just `/customcommand user username info` works.

This would be useful so that players that are not allowed to use this plugin can't use this plugin because they don't know this custom command.

**Comment by lucko** [comment]
> The possibility to change the command to use the LuckPerms commands would be useful.
So that when a different command is configured /lp user username info doesn't work anymore just /customcommand user username info works.

In the case that `/lp` is registered by another plugin, you can use `/luckperms` instead. 

> This would be useful so that players that are not allowed to use this plugin can't use this plugin because they don't know this custom command.

Security by obscurity is bad. If you don't want players to use the plugin, just make sure they don't have permissions for it.
