### ISSUE TITLE
ich brauche Hilfe um die Gruppen zu erstellen

### ISSUE THREAD

**Issue by xXjojojXx** [lucko/LuckPerms#1099]
und die Default Gruppe soll zu Gast direkt
1. Gast
2. Member
3. Vip
4. Admin
5. Owner
Gruppe 1 soll bis Gruppe 5 alles vererben

**Comment by xXjojojXx** [comment]
und durch den Wikipedia Tutorial bin ich nicht durch gestiegen

**Comment by Andre601** [comment]
Please use english next time, since not everyone speaks german. Thanks

Eine gruppe erstellst du mit [`/lp creategroup [name]`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-General#lp-creategroup)
Du kannst eine Gruppe die permissions mit [`/lp group <gruppe> parent add <gruppe welche die die perms vererbt>`](https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-add) erben lassen.
Nutze `/lp group default parent add <deine gast-gruppe>` um default alle perms von gast zu geben.
Andere Möglichkeiten, um die Standard-Gruppe zu ändern findest du [hier](https://github.com/lucko/LuckPerms/wiki/Default-Groups)
