### ISSUE TITLE
Suggestion for promotig

### ISSUE THREAD

**Issue by MysteriousKyle** [lucko/LuckPerms#1107]
Hi, so I want to give multiple people access to give others ranks, but I want to limit it so that they can only give certain ranks. So head builder would only be able to promote someone to t-builder, builder, snr builder, but not have access to give any other ranks. Head admin would be able to promote to tmod, Jr mod and mod, but not to admin or head admin. Manager would be able to promote and demote up to admin, bu not head admin or manager. So basically they would be able to promote only to certain ranks, but can't promote or give themselves higher ranks or the same rank as themselves. Is this possible?

**Comment by Andre601** [comment]
You can create [tracks](https://github.com/lucko/LuckPerms/wiki/Tracks) that those players can use, in order to promote persons to certain ranks.
And to make it sure, can you enable and setup [argument based permission](https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions) to limit, what commands those players can use.

**Comment by MysteriousKyle** [comment]
Oh, Oki. I'mma try that out as soon as I get a chance. Ty for the info 😄
