### ISSUE TITLE
Feature: Multiple server permission

### ISSUE THREAD

**Issue by Jerimu** [lucko/LuckPerms#1124]
As the server says. Permissions like:
/lp group default permission set test.test true server="main-lobby AND arcade-lobby"

Or Like Proxy and lobby = true

**Comment by Andre601** [comment]
idk if that would be a good addition.
You could use the web-editor to have a easy way, to add the same permission for multiple servers, without typing the command over and over again... Just add the permission, change the server and add it again.

**Comment by lucko** [comment]
Not possible due to the way contexts work.
https://github.com/lucko/LuckPerms/wiki/Context

Best solution is to create a custom `server-type` context, and then use `/lp group default permission set test.test true server-type=lobby"`

https://github.com/lucko/LuckPerms/wiki/Context#defining-your-own-contexts

**Comment by Jerimu** [comment]
So if im right. then i could have server=lobby server-type=production and server=lobby server-type=development?
