### ISSUE TITLE
Suffix and prefix not showing!

### ISSUE THREAD

**Issue by Pledix** [lucko/LuckPerms#1179]
Server version: 1.13.1
My chat plugin is EssentialsXChat, EssentialsX and EssentialsXChat version: 2.15.0.45
LuckPerms version: 4.2.58
Vault version: 1.6.7

**Comment by lucko** [comment]
Does the prefix/suffix show up when you run `/lp user <user> info` ? (the user needs to be online for this to work!)

**Comment by Pledix** [comment]
When using this command prefix its seeing. But type message to chat prefix not showing :(

**Comment by lucko** [comment]
If it's showing in the LuckPerms info command, then the issue is not with LuckPerms.

Double check that you're running the latest versions of EssentialsXChat & Vault, and failing that, might be worth looking into any issues with your Essentials Chat config.

There's not much more I can do to help, as the issue isn't related to LuckPerms. You could try asking in the EssX Discord if my suggestions above don't help. :)
