### ISSUE TITLE
lp editor command kicks back 502 - Bad Gateway error

### ISSUE THREAD

**Issue by trinacriamaster** [lucko/LuckPerms#1180]
Hi, well I have this issue.......

It started when I was changing the server reference names in the bungee config file because I was trying to shorten and simplify them. With that I went to each concerning plugin in my bungee server as well as my back end spigot servers to append the change. The result, everything reads and see's eachother, but one I use "lp editor" command, all hell breaks loose and I get a 502 - Bad Gateway error:

https://pastebin.com/vKiE3wjf

I am using the bungee luckperms 4.2.82 as well as the bukkit luck perms 4.2.82 in my spigot servers. What I did already to try to fix it was to undo the name change that I did, but it did not fix. It's like I popped it and its broken now.  My setup consist of one bungee proxy and four spigot servers. They are all using luck perms through MySQL and I am able to edit the sql db manually just fine. The servers are setup properly concerning all the instruction in the wiki's and have been working fine as they should until I appended the server reference name change in the bungee config. Please let me know if you need anything else from me.

EDIT:
From the sounds of it in the discord support chat, its currently a known issue that it's to do with strictly at the web server's layer not the client layer. So my setting changes did nothing to cause this it sounds like.

**Comment by Imortalshard** [comment]
I can confirm this is an issue. I updated both Luckperms-Bungee and Luckperms Bukkit/Spigot to 4.2.82 and after the servers started back up I got the exact same error when opening the editor with /lp editor. I've tried a couple of the other editor commands as well and got the same result. http://prntscr.com/kol8w9

**Comment by EPGMooky** [comment]
I have same problem

**Comment by ProgramOfficial** [comment]
Yes, I am having the exact same issue one a server I am working for at the moment.
The console is showing this error:

`"java.lang.RuntimeException: Got response: 502 - Bad Gateway - <!DOCTYPE html>"`

The full error code is as follows:

`30.08 13:35:53 [Server] WARN java.lang.RuntimeException: Got response: 502 - Bad Gateway - <!DOCTYPE html>
30.08 13:35:53 [Multicraft] Skipped 34 lines due to rate limit (30/s)
30.08 13:35:53 [Server] WARN at me.lucko.luckperms.common.web.HttpClient.exceptionForUnsuccessfulResponse(HttpClient.java:76)
30.08 13:35:53 [Server] WARN at me.lucko.luckperms.common.web.HttpClient.makeCall(HttpClient.java:62)
30.08 13:35:53 [Server] WARN at me.lucko.luckperms.common.web.StandardPastebin.post(StandardPastebin.java:141)
30.08 13:35:53 [Server] WARN at me.lucko.luckperms.common.web.StandardPastebin.postJson(StandardPastebin.java:123)
30.08 13:35:53 [Server] WARN at me.lucko.luckperms.common.commands.misc.EditorCommand.execute(EditorCommand.java:105)`

**Comment by PurelyAliyah** [comment]
Having the same problem.

**Comment by mclegendary1** [comment]
Same problem

**Comment by Ewallee** [comment]
I have the same problem.

**Comment by berk1n** [comment]
I have the same problem.

**Comment by AllPlayed** [comment]
The same problem :(

**Comment by lucko** [comment]
Seems to have been caused by issues with my hosting provider.

All seems ok now!
