### ISSUE TITLE
Failed to validate connection

### ISSUE THREAD

**Issue by MithrandirCraft** [lucko/LuckPerms#1275]
I'm having some issues with the LP <-> MariaDB connection
`[13:50:18 WARN]: luckperms - Failed to validate connection me.lucko.luckperms.lib.mariadb.MariaDbConnection@40616e7f (Connection.setNetworkTimeout cannot be called on a closed connection)`
Checked the LP wiki and found that a certain threshold should be lower than the database's, and it actually is. Any ideas?
Happened after switching hosts.

LP: 4.2.22
Spigot: 1.12.2

**Comment by BrainStone** [comment]
Try lowering the value in the LP config.

**Comment by MithrandirCraft** [comment]
Lowered maximum-lifetime from 1800000 to half the ammount: 900000
Will report if the error persists, allthough it does spam quite constantly and usually if any changes to permissions are done.

**Comment by lucko** [comment]
All the info I can give relating to this issue is here:

https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-no-operations-allowed-after-connection-closed-error

**Comment by MithrandirCraft** [comment]
@lucko Then I'm sentenced.
Did you read my ticket? I already checked that section of the wiki and verified I'm complying with it. It happens even after. I have full control of the database so if that where the case I could fix it.

**Comment by lucko** [comment]
Yes I did read what you said - what makes you think I didn't?

> All the info I can give relating to this issue is here

That statement is still correct - the issue you're experiencing is not being caused by or at all related to LuckPerms - as explained at the top of the "Storage system errors" wiki page.

> Importantly:
> * **If the error originates from the driver - it is *not* being caused by LuckPerms.**
> * You *may* have experienced a bug in the driver itself, however this is unlikely
> * The most likely cause is that something is setup or configured incorrectly.

The wiki page contains some common configuration mistakes, alongside my own research about how they can be resolved.

If changing the configuration values didn't help fix the problem, then you'll have to look around for other potential causes. Perhaps some other system is closing the connections early, might be a networking issue? Maybe the MySQL wait_timeout setting is being overridden by something else? Maybe it needs a restart to be applied?

Unfortunately all I can offer you is guesses. MySQL isn't my software, and I'm not an expert on the way the MySQL server operates.

**Comment by BrainStone** [comment]
@MithrandirCraft MariaDB has 3 configs to check for when looking at these values.

Also it's 480min not 480h. Another value to check is `interactive_timeout`.  
One more thing that could easily cause this if the MariaDB server is on a different host. Then the connections could be killed by the routing hardware between the two for inactivity.
Lowering the value in LP down to a minute is still fine.

**Comment by Wastinqs** [comment]
Same here, all above didn't work out.
