### ISSUE TITLE
Suggestion: One server permission groups

### ISSUE THREAD

**Issue by M4tZeSS** [lucko/LuckPerms#1303]
Currently, if I understand it correctly, if a permission needs to be applied to only 1 server in the bungee network, for instance server1, you would need to set the options to `server=server1`. But if you need to do this for a large quantity of permissions, it would be very time consuming.

My suggestion is, if it doesn't already exist, an option in the `creategroup` command, to set the server for the group, and an option to set it that the group will only be visible in the server specified.

Thanks,
-Mathis

**Comment by Imortalshard** [comment]
When you apply a group to a user (or another group as a parent) you are able to use `server=<servername>` Otherwise, you can use the web-editor to add all the permissions to the group and if you change the server field to the server name, all new permissions you make will be in that server already. So you only have to change the actual permission and it will add the server context.

**Comment by M4tZeSS** [comment]
I know, but it will still show the group in the whole network, which is not really handy in some use cases.

**Comment by BrainStone** [comment]
I don’t see how certain groups designed for one server showing up on all servers is an issue. I mean it’s just visible for admins in the first place.

**Comment by lucko** [comment]
Agree with Brainstone, I don't see how this is an issue.

I prefer being able to see everything about a group, and not have data hidden depending on where you run the command in the network.

**Comment by M4tZeSS** [comment]
I get that you prefer to be able to see all groups, but I think it should atleast be an option to hide some groups depending on which server you're in if you feel like me.

Thanks,
-Mathis
