### ISSUE TITLE
Prefixcolor

### ISSUE THREAD

**Issue by arkobat** [lucko/LuckPerms#1315]
Hello

I've some troubles with figuring out the prefix system.
I've 2 tracks, a donator track and a staff track.
Prefixes on "donator track" all have a weight between 10 and 50.
Prefixes on "staff track" all have a weight between 100 and 125.

The prefix is always show correct (The highest weight).
So for mods, it's [Mod], and for members, it's [Member] etc. All work correctly.

The member's prefix is `&6[&2Medlem&6]&2`, with a weight of 10
The mods prefix is `&6[&9Mod&6]&9` with a weight of 105
Therefore the placeholder {prefixcolor} should be blue.

If a player both have the default group (which inherits member), and moderator, the prefix color is &2.
If a player only has moderator, the prefix color is &9, which it should be in both cases

The staff ranks do not inherit the donator ranks, so they need to have a rank on both tracks.

Luckperms config: https://hastebin.com/okofekihav.shell
Picture of meta info for a mod: https://gyazo.com/4a1425c994890d960b10b89c252b8977
Where there is written `test`, i've used the command `/papi parse DanishJohnJohn %mvdw_prefixcolor%test`

Server version: PaperSpigot 1.13.2
LuckPerms version: 4.3.17
PAPI version: 2.9.2
LuckPerms part in latest.log, including when Vault registers LP: https://hastebin.com/ahefukoyeg.md

**Comment by BiGUNMAN** [comment]
You'll most likely need to solve your problem on your own since it doesn't appear to be LuckPerms related. I believe it is related to your %mvdw_prefixcolor% - does this placeholder parse correctly in /papi parse?

After the addition of `primary-group-calculation: parents-by-weight` I've had to readjust how our placeholders work by making sure our groups have the correct weights so that Vault returns the most relevant/high weighing rank to other plugins. I recommend investigating this as well.

**Comment by lucko** [comment]
Indeed, the prefixcolor placeholder isn't provided by LuckPerms, you'd have to ask the author of Mvdw placeholders.
