### ISSUE TITLE
lost connection: Disconnected

### ISSUE THREAD

**Issue by caandalek** [lucko/LuckPerms#1329]
https://i.gyazo.com/thumb/1200/32ea04f601eb1fc79d369e83d6dfaf41-png.jpg
Players cannot log in to the server after a time. I get the "lost connection: Disconnected" error.

In this picture I wrote the command /lp sync and it was frozen.
At the bottom, /lp is not pissed even though I type.

**Comment by BrainStone** [comment]
From what I see, I’m not sure if it’s LuckPerms causing LuckPerms to freeze or if some other plugin is doing terrible things, but LP straight up freezing and becoming non-responsive is not what should happen.

That’s all I can tell from this info and previous conversations on GitHub.

**Comment by lucko** [comment]
I replied already on Discord, but I'll post my response here for the record. 😄 

>  Luck - Last Monday at 18:10
Still doesn't mean it's being caused by LuckPerms
Could be related to the server itself, or the network, or the underlying box resources (CPU, memory etc)

> Furkan Balcı - Last Monday at 18:15
Why do you always think that?
Maybe the problem really is in the LuckPerms plugin?
Why not call your add-on instead of looking for a solution?
I'm just trying to make sure this doesn't happen to other people. I want help.
I have this problem on 2 different machines.

> MD (not that one) - Last Monday at 18:17
Did you try removing LuckPerms on both machines?

> Furkan Balcı - Last Monday at 18:18
When LuckPerms removes it, there is no such problem. I've tried.
MD (not that one)Last Monday at 18:18
And any other plugin?

> Furkan Balcı - Last Monday at 18:19
No, as you can see, there are 1 plugins available. He also LuckPerms

> Luck - Last Monday at 18:21
I think that because there is absolutely nothing you've shown me to suggest it's a LP issue
And thousands of others use the plugin in the same way with no issues whatsoever
The logical conclusion is that it's being caused by something else

I need **something** to be able to do anything about this issue if it really is LuckPerms. Some sort of error message originating from or including LuckPerms, a crash log, some sort of profiler output, etc etc. Until then, I cannot do anything.
