### ISSUE TITLE
Permissions not working.

### ISSUE THREAD

**Issue by reageer** [lucko/LuckPerms#1331]
Hello! I really like this plugin, but I got a big issue with it.

I migrated from PermissionsEx to this plugin because PermissionsEx wasn't working properly. So, I moved to this plugin and I have the exact same problem here that I had with PEX. I don't know if I am just a total idiot for not doing something that I needed to do, but I tried it three times now and all in a different way.

When I add someone to a group, they don't get the permissions...

I've tried; using the migrate command, using the web editor, and using the in-game commands.

I really don't know what I am doing wrong, since this problem is apparently happening to me with every permission plugin. Any help would be appreciated! :)

**Comment by Andre601** [comment]
[Essentials]: https://github.com/lucko/LuckPerms/wiki/Installation#essentials
[Getting started with LP]: https://github.com/lucko/LuckPerms/wiki/Usage#getting-started
[Prefix, Suffix and Meta]: https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta

LuckPerms doesn't manage the chat. It only provides the groups, prefixes and suffixes which other plugins can use (for Example through Vaults API).

Vault and a chat plugin that supports it, need to be installed in order to show prefixes in chat.
The same goes for basically any other place you want prefixes to appear (Tab, scoreboard, etc.)

More info:
* [Essentials]
* [Getting started with LP]
* [Prefix, Suffix and Meta]
