### ISSUE TITLE
Command to add time to a temporary permission

### ISSUE THREAD

**Issue by GoogleSites** [lucko/LuckPerms#1361]
Idea: A command (/LP user <player> temp add permission.node <time>. If the player does not have the permission node already, it will just add that much time starting from 0

**Comment by Andre601** [comment]
[temp]: https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp
You mean temporary permissions?

If yes, please check the wiki, since this already exists for LuckPerms. The command is:
[`/lp user/group <user/group> permission settemp <permission> <true/false> <time> [modifier] [context...]`][temp]

**Comment by BrainStone** [comment]
The modifier you need is `accumulate`. If the permission does not exist already it is just added. The modifiers only matter if there’s a temporary permission of that node already (needs to be an exact match with permission and context).

So for the future, please check the existing commands before suggesting new ones.

**Comment by GoogleSites** [comment]
Thanks for the quick response! I'll make sure to do that in the future :)
