### ISSUE TITLE
[BUG] Accent

### ISSUE THREAD

**Issue by SeDark** [lucko/LuckPerms#1363]
Yesterday I upgraded from version 4.2.51 to 4.3.17 and apparently I can not use accents in the permissions.

https://pastebin.com/JWscjyCR

Any idea?

**Comment by electronicboy** [comment]
LP recently changed it's schema to allow utf8, but it's not an automatic conversion;
Easiest method is to export your permissions, drop the tables and let LP create them with the new options

Otherwise, you'll need to convert the schema yourself, if you know how to use mysql, it's as easy as deleting an index and converting the collation to utf8mb4 so that the database can store unicode
