### ISSUE TITLE
verbose shooting irrelevant checks for luckperms?

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#1381]
Is this how it's supposed to be?
Was trying to determine why my staff can't do **/lp user andrewkm info** (something I've now solved) and was getting this during verbose:

https://pastebin.com/raw/JskiC81n

Essentials making verbose kind of useless for debugging luck perms permissions problems. It basically checked for every luckperms perm?

**Comment by lucko** [comment]
LP will check for permissions for all subcommands (recursively) in order to determine what sort of feedback to give the player.

For example, if you just run `/lp` - the plugin will check to see if you can use any of the subcommands, in order to display some sort of help menu.

Sooo, this behaviour is normal.

**Comment by andrewkm** [comment]
Thank you for explaining :)
