### ISSUE TITLE
True/False permission node change

### ISSUE THREAD

**Issue by TheRealLogical** [lucko/LuckPerms#1388]
Basically, on discord I was talking about this, and the mod said I should post it here.

Let’s say you set a permission for a player called test.
/lp user test permission set test.permission false

If I want to make that permission TRUE, Then I have to delete the permission, then I have to redo the permission with true at the end. 

My suggestion is that you can toggle the permissions from true to false without resetting the permission.

**Comment by PrincessRTFM** [comment]
Do you mean toggle as in a new `toggle` subcommand, or as in overwriting the existing one when using `set`? Personally, I'd think the second one would be most useful because you could just `set` the permission regardless of whether they have it, but I suppose there could be some use cases for the first.

**Comment by TheRealLogical** [comment]
I meant the set one

**Comment by bloodmc** [comment]
This is definitely not the case on Sponge servers. If you set a permission, you do not have to remove it to change it. Not sure how it works for Spigot/Paper servers.

**Comment by TheRealLogical** [comment]
It doesn’t work for spigot servers :P

**Comment by Foxtrek64** [comment]
Just tested this. I'm running this on Spigot 1.13.2, LP version 4.3.73. Denying myself `bukkit.command.op` and then allowing it resulted in an allow. This functions as @PrincessRTFM described in their post.

Commands were run in this order:
```
/ess version
/perm user Foxtrek_64 permission set bukkit.command.op false
/perm user Foxtrek_64 permission set bukkit.command.op true
/perm user Foxtrek_64 permission info
```

![image](https://user-images.githubusercontent.com/7003081/51895948-01cd0200-2371-11e9-86a9-c586f6ff040b.png)

**Comment by Andre601** [comment]
Some people here forget, that a web editor exists, where you can basically toggle the false to true and oposite :P 
Just type `/lp user <user> editor` change the value, save and then use the generated command.
But I still agree that this could/should be an addition, if not already possible.

**Comment by Foxtrek64** [comment]
I agree with PrincessRTFM. @TheRealLogical What is your server version and LP version? You can get these by running the following:

```
/version (or /ess version)
/lp info
```

If you could, give us these values or post a screenshot like I did.

**Comment by TheRealLogical** [comment]
I run LuckPerms on a 1.8.8 Spigot server.

**Comment by Foxtrek64** [comment]
Please run the commands suggested in my last comment and provide us with the output of those commands.

Additionally, please provide us with the behavior your experience when trying to set a permission node to `true` when it had been previously set to false, as well as what you expect to happen.

**Comment by lucko** [comment]
A haaa, I had forgotten this was added already! 😅 

Since this commit, this behaviour should already be happening: https://github.com/lucko/LuckPerms/commit/d28170cc3f03583edc3d8cbca1427133bdf99445

Also, talk of the web editor is irrelevant - I've hidden those comments.



Sooo, yes, seems like a bug if your'e not seeing this behaviour already. @TheRealLogical Can you make sure you're using the latest version, and then give us the commands you tried to run.

**Comment by TheRealLogical** [comment]
Will do, I’ll tell you if it works afterwards.
