### ISSUE TITLE
kick on join mysql connection issue

### ISSUE THREAD

**Issue by mmuziek** [lucko/LuckPerms#1391]
when a user tries to join a big error gets into the console.
also on startup the same issue appears it always worked but since last update it fails to work.
here is the debug report : https://hastebin.com/raw/hesamoweci
and console log parts:
https://pastebin.com/QWJ1Hwnu

**Comment by BrainStone** [comment]
The error is nowhere to be found.  
Would be nice to just have the error.

**Comment by mmuziek** [comment]
oops the logfile was broken here is the snipped errors : https://pastebin.com/dgm2g2Fq

**Comment by lucko** [comment]
Can you show the full log that includes the error?

I need to know when during the servers operation that message is being printed.

**Comment by mmuziek** [comment]
here you go https://pastebin.com/QTwpEhpD

**Comment by lucko** [comment]
Line 3247 - you can see that your server has started shutting down (LuckPerms has disabled) - but your server is still accepting logins.

That's why you're seeing those errors.

Seems to be an issue with the `com.razorblur.mcguicontrol` plugin causing your server to stop responding (it's doing some sort of database request on the main thread.

I'm guessing the SpigotLib plugin is what's shutting everything down.


> [01:04:11] [pool-27-thread-1/INFO]: ============== SpigotLib Crash Reporter ==============
Your server has been detected having 0 TPS 4 times a row, which means that with high probability it crashed / frozen down. This crash report will help for your developers to detect what's causing the crash. This is NOT an error in SpigotLib, but it's one of it's features, so only contact gyuriX for fixing the error caused this crash if you can pay for it.

Either way, definitely not a LP issue.
