### ISSUE TITLE
BungeeCord IllegalStateException: No permissions data present for player

### ISSUE THREAD

**Issue by LudnicaKiller** [lucko/LuckPerms#1397]
https://pastebin.com/0QvFYZjq

I'm getting this error all the time in console even if that player is online and offline and sometimes for online players with "/find" it says they're offline..
Don't know what I did wrong and is it even my fault.. Users in that error doesn't have any permissions on the LuckPerms.

config.yml: https://pastebin.com/Wa5MLNWY

groups:
vlasnik.yml : https://pastebin.com/MtT1LYBy
skin.yml : https://pastebin.com/JjVW3LvH
mod.yml : https://pastebin.com/XUhMQR7y
default.yml : https://pastebin.com/5XVkYjF5
admin.yml : https://pastebin.com/NUeK6v36

This server is running BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:a12bb4c:1388 by md_5

**Comment by lucko** [comment]
Could you restart your proxy, and then try logging in.

If the error still shows, could you send over the full log?

**Comment by LudnicaKiller** [comment]
I did it couple of times and still receiving this.

**Comment by lucko** [comment]
> If the error still shows, could you send over the full log?

**Comment by lucko** [comment]
That's not the full log.

`31.01 22:24:21 [Multicraft] Skipped 74 lines due to rate limit (30/s)`

I need to see the full proxy log file.

Please just follow my instructions exactly - I'm not trying to be difficult, quite the opposite, I need the steps to be followed in order to help you.

> Could you restart your proxy, and then try logging in.
If the error still shows, could you send over the full log?
