### ISSUE TITLE
Can't seem to load any prefixes in chat - essentials login chat does display it on welcome

### ISSUE THREAD

**Issue by daronhudson** [lucko/LuckPerms#1427]
I've got prefixes setup for groups(triple checked)
The essentials chat menu brings up the edited version of the name including the prefix and all that but it doesn't actually display it in chat. No idea why. I've been messing around with it for a few hours now to no luck.

EDIT: it literally shows everywhere except the message shown in chat - console displays it and so does discord

**Comment by Imortalshard** [comment]
Hi daronhudson,

If you're wanting to use Essentials chat formating to display the prefixes from Luckperms. Please make sure you use EssentialsX instead of Essentials (the X is important) Also make sure you have vault installed as well. You can find the latest version of EssentialsX & EssentialsXChat here:
https://ci.ender.zone/job/EssentialsX/
