### ISSUE TITLE
MySQL SSL Problem

### ISSUE THREAD

**Issue by Mattx8y** [lucko/LuckPerms#1430]
I'm trying to connect to a MySQL server in order to use global ranks (BungeeCord network). However, I got this error when starting my SkyBlock server:

https://mclo.gs/GSnau3n

At first, I thought it was a connection error, however, it's consistent (it happens every time I restart the server) AND the MySQL connection works fine on both the lobby server and the BungeeCord proxy.

Does anyone know why this is happening?

**Comment by Mattx8y** [comment]
LuckPerms also constantly spams this line into the console:

https://mclo.gs/GSnau3n#L195

**Comment by Mattx8y** [comment]
oops

**Comment by Foxtrek64** [comment]
So you seem to have a couple problems here. However, it's this problem that's causing the connection to outright fail.

See [line 30](https://mclo.gs/GSnau3n#L30) where it reports the following:
```[17:10:25 WARN]: Caused by: me.lucko.luckperms.lib.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: User JPIcG8LzOp already has more than 'max_user_connections' active connections```

For this issue, read this article on the wiki regarding [storage system errors](https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-exceeded-max-connections). The fix should be on this page.

For the SSL issue, if you're connecting to a SQL Server running on an internal network (i.e. it's not traversing the internet), you can explicitly disable SSL with `useSSL=false` in your mysql config and that will get rid of those errors. Otherwise, you can self-sign a certificate and use that for authentication.

If you're self-hosting through a VPS, then Digital Ocean's article on [securing a MySQL or MariaDB server](https://www.digitalocean.com/community/tutorials/how-to-secure-mysql-and-mariadb-databases-in-a-linux-vps) may be of use to you. Otherwise, I recommend reaching out to your hosting service and informing them of the SSL errors.

**Comment by Imortalshard** [comment]
Hi Mattx8y,

For details on how to resolve the MySQL SSL error, please refer to this page:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-ssl-errors

For details on how to resolve the _max_user_connetions_ error, please refer to this page:
https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#mysql-exceeded-max-connections
