### ISSUE TITLE
Easier subcommands / subcommand aliases

### ISSUE THREAD

**Issue by TheJavaDev** [lucko/LuckPerms#1465]
I feel like some subcommands should be changed / have an alias like:
/lp listtracks -> /lp tracks
/lp listgroups -> /lp groups

Also a universal /lp delete command would be easier to use, like /lp delete <group/track>

This is a fantastic plugin and is very easy to use, these are just some suggestions
It just feels a bit more intuitive to me

**Comment by lucko** [comment]
I'm going to be revising the aliases soon, although, it will most likely be to remove a lot of them.

Tried to find my previous comment on this - but haven't been able to. Basically, the issue with adding aliases is that it can be confusing/misleading when the aliases do weird things.

For example, there's an alias from `/lp user <user> set <permission>` to the actual command, `/lp user <user> permission set <permission>`.

However, users can mix this up, and run `/lp user <user> set permission <permission>` - which will actually set the permission `permission`.

And that's why I'm leaning towards scrapping aliases all together.

**Comment by lucko** [comment]
Aliases were removed in v5 - I still feel this is the right direction for the plugin. It will make things easier for everyone in the long run if there's only one alias for each command.
