### ISSUE TITLE
Commands not appearing in the Web Editor?

### ISSUE THREAD

**Issue by Crumbzttv** [lucko/LuckPerms#1491]
I have the latest version of LuckPerms for Spongeforge. 

I have been configuring/sorting out the commands each group can use for my Pixelmon server, up until trying again just now. None of the basic minecraft commands such as minecraft.command.ban even show up on the "Permission" section and none of my pixelmon.commands are showing up either. 

The only commands it is allowing me to mess with are with Nucleus commands and also luckperms itself, nothing else is showing up. I want to add new plug-ins but I can't get permissions for the commands, even if I just type in the permission myself and enable it.

**Comment by BrainStone** [comment]
The permissions listed in the drop down of the web editor are just a suggestion. So you can use any permissions.

The permissions that show up there are the permissions that have been checked since the server is running. To populate the list, you can run `/help`.

So you also need to save the changes. In the top right corner is a save icon. Click that and then run the command it shows you on the server.

**Comment by f43tgdrdgdfbd** [comment]
> The permissions listed in the drop down of the web editor are just a suggestion. So you can use any permissions.
> 
> The permissions that show up there are the permissions that have been checked since the server is running. To populate the list, you can run `/help`.
> 
> So you also need to save the changes. In the top right corner is a save icon. Click that and then run the command it shows you on the server.

hey i have the same issue. but what did you mean by /help? (yes ik this post is 3 years old)
