### ISSUE TITLE
Luck perms disconnecting issue

### ISSUE THREAD

**Issue by AlekseyTitov99** [lucko/LuckPerms#1492]
Hello,

My luckperms database keeps getting d/ced randomly and kicks a bunch of people https://pastebin.com/00Wx3dGJ

Once it loses connections it also drops connections from other servers for a couple of seconds not allowing them to connect on there too.

Servers use separated databases for luckperms but are on the same machine.

Any ideas why this is happening ?

**Comment by Andre601** [comment]
[`Connection is not available, request timed out after 15051ms.`](https://github.com/lucko/LuckPerms/wiki/Storage-system-errors#luckperms-cannot-connect-to-my-mysql-server)

**Comment by AlekseyTitov99** [comment]
Right, its randomly being disconnected, some days it might happen, others might not. Once it does disconnect it throws a lot of IOException errors which disconnects people.

**Comment by Andre601** [comment]
Whatever the reason is, it is not a fault on LPs side.
It is a most likely a misconfiguration on either the LP side (config.yml) or on your database's side.

LuckPerms does nothing wrong here. The error only points out that it lost connection to the database, due to a timeout.
I linked the part of a wiki that lists the possible causes of this, but again: It's not an issue on LuckPerms side and more a misconfiguration.

**Comment by lucko** [comment]
The log is also showing

```
[14:51:30] [Connect Thread/INFO]: [Connect] Lost connection to the cloud, reconnecting
```

so your server is losing connection to LilyPad too - suggesting that more general networking problems is the cause.

Not really much I can do to help - perhaps an issue with your hosting provider? Or is the database on the same server as Lily Connect - maybe that box is overloaded?
