### ISSUE TITLE
LuckPerms 4.4.18 and 4.4.19 - Gson StackOverflowError

### ISSUE THREAD

**Issue by Porama6400** [lucko/LuckPerms#1525]
Executing command on console was fine. but player executing command that they **have permission** to will result in lost connection, or sometimes cause command error for some plugin

The text "You do not have permission to execute this command!" also turn white when using affected version of luckperms, not sure if those info will help

BungeeCord : latest
Errors only occur when using LuckPerms 4.4.18+
No error while initialize

This is error when I try to execute /find
https://gist.github.com/Porama6400/53cf73b98f6b42f29e4fdd48ae003013

**Comment by SimonOrJ** [comment]
I have the same error.  Here are the relevant parts of the log.

https://hastebin.com/azekalevon.cs

First stack happens after user with wrong MC version tries to join.
Second stack happens when a player runs custom command that uses TextComponent to get the result.

It never mentioned LuckPerms once, so it took me a while to find out that LuckPerms is the culprit of the issue.  I'm not sure if the logs will help in debugging the problem, but it should help on knowing what libraries are affected by it.

**Comment by Louuuwh** [comment]
I think the fact that the messages of permission are no longer coloured and they may be White may finally help.

**Comment by lucko** [comment]
https://github.com/KyoriPowered/text-extras/pull/7
