### ISSUE TITLE
Bungee Permissions Sync

### ISSUE THREAD

**Issue by tomkeuper** [lucko/LuckPerms#1529]
Suggestion

Hello I am trying to setup my network and when i am adding staff ranks I need to set them up on each and every server locally, this means that I need to go onto every server and add all the ban permssions etc. It could be a LOT easier is there is an option to add them to the bungeecord version of LP and it synchronizes it across all the servers. 
I know there is a sync command but as far as I know it syns all the permissions and I would like to specify what commands are being synced because every server has its own commands that staff members can use and it should not copy those.

My Idea is like a menu to add the global staff commands in the bungee version and then a icon near the permission if you open the editor of the minecraft server itself, to know that the command is from the bungee server LP install.

**Comment by BrainStone** [comment]
Check the wiki page „Network Installation“. It explains how to set up LP so the permissions sync across all servers.

**Comment by Andre601** [comment]
[network-installation]: https://github.com/lucko/LuckPerms/wiki/Network-Installation

The sync command doesn't just sync the permissions.
It performs an update task that, depending on what is set as a messaging-service, sends a ping to all LP instances on the different servers and tell them to update their storage of players, groups and permissions so that groups and permissions can be synchronized.
But this is also a thing that LP normally does on its own when a permission, group or user is updated.

To achieve this you need the following set up and working:
- A remote database (like MySQL) that every LP instance is connected to (Same login cridentials.)
- A messaging-service that is used to send update-notifications. By default does LP use SQL-messaging when a MySQL database is used.

Please check the [Network-installation] page on the wiki since it explains this stuff I mentioned here and is a big help on troubleshooting issues.

**Comment by tomkeuper** [comment]
When I use sync like that with a remote database does it remove any other permissions that are not in the list of permissions that i am syncing from?

**Comment by Andre601** [comment]
The syncing will only work if all instances of LP share the exact same database, meaning that they share the same set of permissions, groups, etc.
Again. Check the page I linked because it explains how you properly setup LP with everything needed to work on a server-network. The issue-tracker isn't really for general support.

**Comment by tomkeuper** [comment]
I get that this is not for general support but what i am getting is not what i ment. I will try to explain better.

I would like a main permissions list per group that syncs across all servers.
So [A] is the main server or bungeecord and B and C are backend game servers.

I would like it so when i want to change a permission for for example mods i would go into the lp editor of [A] that will push an update to [B] and [C]. But when i am making changes to [B] to give a mod plot kick permissions, it doesnt show up on [C] only the permissions of the ones that are set in [A] and its own permissions will be there.

**Comment by BrainStone** [comment]
If you have a proper network setup, you can have per server and per world permissions, no issue.  
The wiki page Contexts is your friend.

And in general suggestions are always better first discussed on the Discord. Because chances are it’s either already implemented/possible (in a slightly different way than you imagine) or has been asked before and either been put on the to do list or rejected.
