### ISSUE TITLE
Add an option to limit the number of prefix's that can be shown

### ISSUE THREAD

**Issue by Tsugeta7** [lucko/LuckPerms#1532]
As title says. Adding a config option that allows you to limit the number of prefix's that'll be shown in game. Example being if you have 7 prefix groups or tracks listed in your config, LP limits it to only show the highest 3 that a player has.

**Comment by lucko** [comment]
This is possible already.

https://github.com/lucko/LuckPerms/wiki/Prefix-&-Suffix-Stacking

**Comment by BrainStone** [comment]
I don’t think you understood what’s been asked here.

The thing is, imagine you have like 10 lines for your prefix stacking. For some players that’ll result in only a few prefix and others get more than let’s say 3. Now the request is to add a way to limit the sum of shown prefixes to 3 or less. No matter if there would be more than 3.

**Comment by lucko** [comment]
> MrCreepysBro  Today at 10:28
Luck, I guess you didn't understand what I meant in my GitHub suggestion. I'm fully aware about the stacking feature. However, what I was suggesting was if you have 6 groups on your stacking format, and someone is apart of 5 of them, having an option to only show the highest 3 rather than all 6 prefixes since currently in the plugin, there is no way to do that
I asked here before if it was possible and was told from one of your mods that it wasn't and to make a suggestion on GitHub. Hope that clears it up.


> Luck  Today at 10:54
Right ok I see what you mean
I can't think of a way to implement that easily in the current stacking system
And it seems quite niche if I'm honest

**Comment by lucko** [comment]
Open to suggestions :)

**Comment by BrainStone** [comment]
Maybe specifying the same key (like `highest`) has the effect that the second takes the second best match, etc.

**Comment by lucko** [comment]
My opinion is that this is still too niche. 

Would be possible to do through the API, but not something I think that belongs in the main plugin. A quality PR implementing this functionality would likely still be accepted, but it's not something I'm going to work on. :)
