### ISSUE TITLE
LuckPerms isn't recognizing all permissions from plugins

### ISSUE THREAD

**Issue by tomaspena-iso** [lucko/LuckPerms#1554]
When using the online editor, LuckPerms auto fills only a fraction of the permissions from plugins. For example, only a few Craftbook perms appear when typing craftbook.mech.* but not the ones that I need such as craftbook.mech.elevator.
Here's a screenshot of the problem.

![61253585_890177371374764_8587879845285855232_n](https://user-images.githubusercontent.com/51104490/58447438-62c3d700-80d2-11e9-9283-6c842196bdec.png)

**Comment by Turbotailz** [comment]
This is working as intended.

Luckperms cant possibly know every single permission available on your server, it only keeps track of permissions that have been checked since the last server restart.

If you want to populate the list, you could try running /help but this probably won't bring up everything.
