### ISSUE TITLE
Troubles

### ISSUE THREAD

**Issue by MrLaco** [lucko/LuckPerms#1567]
Hello. There was such a problem: when receiving LuckPerms data through Vault, the following error occurs (screen attachments), and such a problem is only with your plugin, the rest of the rights systems transmit data without errors. What can be wrong?

**Comment by MrLaco** [comment]
Error: https://ibb.co/KVYHzBJ

**Comment by MrLaco** [comment]
Help me, please!

**Comment by Andre601** [comment]
This is not directly LP related.

The issue is that a plugin tries to check for permissions on the main server thread which should be avoided since it can cause lags or other performance issues.
LP intentionally returns a RuntimeException with the following message (As seen in the image):
```
The operation to load user data for '<UUID>' was canceled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to load data for offline players from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternativelym, server admins can disable this catch by setting 'vault-unsafe-lookups' to true in the LP config, but should consider the consequenzes (lag) before doing so.
```

So in order to "fix" this, you have two options:
1. Let the developer of the plugin (In this case it's either CommandNPC or your SkyBlock plugin) that made that unsafe check know about this issue to hope he fixes it or
2. Set this option here to true:
https://github.com/lucko/LuckPerms/blob/ffe6c24b53e75af2aa94def451c183795026fd36/bukkit/src/main/resources/config.yml#L506-L515
