### ISSUE TITLE
Wildcards in sponge

### ISSUE THREAD

**Issue by XakepSDK** [lucko/LuckPerms#1624]
Can you please raise giant warning ASCII image, when someone uses wildcards, even if they are enabled in config?
Many people ask for help because of "unexpected" issues with wildcards.

**Comment by Andre601** [comment]
Not really needed. It's their problem when they use wildcard permissions.

**Comment by XakepSDK** [comment]
And with that ASCII image they will know, that this is their fault.
Current warning is not noticeable

**Comment by Andre601** [comment]
Having a big sign would be overkill and only spam the console more

**Comment by BrainStone** [comment]
Also be aware that you will have to use wildcards when you're running a mixed network.

**Comment by lucko** [comment]
I'm against adding this - they're an intended feature of the plugin, and implicit wildcards are an intended feature of Sponge.

I don't see why users should be warned about their use.

**Comment by XakepSDK** [comment]
Then maybe add warning when they use `*` as permission?
Not `parent.node.*`, but just `*`
This literally breaks many plugins

**Comment by ktole1999** [comment]
i was told by nucleus folks that any wildcard will cause issues whether nucleus or nucleus.* so I am confused. I would rather not have to write out a huge list of perms for my admins if I don't have to.

**Comment by BrainStone** [comment]
@ktole1999 not related to this. Though the issues are plugin specific. Using wildcards works for some plugins, but not others. And Nuceleus is one of those plugins. (GriefPrevention is another (but for totally different reasons)). Nucleus provides a command that will setup the permissions for you. And GriefPrevention has a wildcard you can use.  
Though in any case it is not LP's job to police your permissions. If some plugins have issues with global wildcards (any plugin with "negative permissions" (permissions you don't want/that turn something off rather than on)) or plugin wildcards (like `nucelus` or `nucleus.*`) then it's the job of those plugins to make the admins aware, not LP.

**Comment by ktole1999** [comment]
fair enough, just trying to understand.

**Comment by XakepSDK** [comment]
It's not job of those plugins. Sponge does not forbids wildcard, but also does not tolerate them.
https://docs.spongepowered.org/stable/en/plugin/permissions.html
Check out note.

**Comment by BrainStone** [comment]
Incorrect. All that says is that Sponge has never intended for Bukkit style wildcards to be implemented. Just LP does. Mainly for compatibility reasons.

And yes. If wildcards break a plugin (Talking about the default wildcards of the platform. `nucleus` breaks Nuceleus a bit. And `griefprevention` breaks GriefPrevention pretty much completely. And without LP) it is the plugin's job to make the admin at least aware (like GP does). Or to provide a convinient way to still setup permissions either through designated wildcards (like GP) or a command that sets up the individual permissions for you (like Nucleus).
