### ISSUE TITLE
use-server-properties-name not working in 1.14.3

### ISSUE THREAD

**Issue by Tinkot** [lucko/LuckPerms#1645]
When using `use-server-properties-name:true` it throws a error

Might be because Bukkit is not instantiated when loading the plugins

see stacktrace -> https://i.ibb.co/QQ0cWP2/Schermafbeelding-2019-07-26-om-15-41-39.png

**Comment by Andre601** [comment]
Since the release of MC 1.14 (I think) is there no option in the server.properties to set a server name, therefore causing this error.
Just keep this setting to false and instead set a server name in the LP config directly (Should be the first option).

Also, should you update to 1.14.4 since it's a bit more stable and has better performance.

**Comment by Tinkot** [comment]
i see, didn't notice it got removed
