### ISSUE TITLE
Possible Feature to be added

### ISSUE THREAD

**Issue by battery3996** [lucko/LuckPerms#1647]
So I was looking at Ultra Permissions mainly bc they have an easy to use in-game GUI that server owners can use. Very intuitive. I was wondering if we could something very, very, very similar to that. I have been using the LP editor however the in-game GUI seems a bit better especially for server owner beginners like myself.

Im having to stick with this plugin mainly because GriefDefender uses Contexts that LP has... also it was highly recommended to me because its so much more lite weight and server friendly.

**Comment by Andre601** [comment]
An ingame GUI comes with some limitations like you're restricted to 54 Slots in total and you can only use items that are available in MC. Also, does it add a version-dependent part that makes it difficult to support versions below 1.13 or above it due to Item name changes before/after 1.13

A web editor has much more options, can easily be expanded and improved and you aren't limited by what Minecraft (or Spigot) offers.

If you still want to use an ingame GUI, then you can find a plugin called [LuckPerms in GUI](https://www.spigotmc.org/resources/luckperms-in-gui.53460/) that adds exactly what you want.
Note however that we do not provide support for this plugin on the LP Discord.

This suggestion was brought up a lot and Luck gave similar/the same reasons each time why it won't be added.
