### ISSUE TITLE
Only allowing users to target themselves

### ISSUE THREAD

**Issue by jessica-jorgenson** [lucko/LuckPerms#1670]
Hey!
I want my players to be able to use the /clear and in certain worlds, change their gamemode, but I don't want them able to change anyone else's gamemode (besides admins).
Any help? I thought [this](https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions#modify-self) might help me, but I'm not sure if this is just Luck Perms or overall.

Thanks!

**Comment by Andre601** [comment]
The argument based command permissions are **only** for LuckPerms commands.
There is no way (And no real reason) for LuckPerms to have this for other plugins. Especially since it could conflict with permissions the other plugins already have set.

You have to look at the permissions that the plugins use for the commands... In most cases do they have two separate permissions for using the command on yourself and others.

This is nothing we can help you with. You have to find the information yourself.
