### ISSUE TITLE
Luck Perms Error

### ISSUE THREAD

**Issue by malsem** [lucko/LuckPerms#1690]
https://pastebin.com/9w6sxPkU

Is this error caused from luck perms?

**Comment by Andre601** [comment]
There are multiple errors in this Pastebin.
The first one seems to be an issue with LPs storage. Try to delete the libs folder inside the LuckPerms folder to let LP redownload those libraries it needs.

The crash (or thread dump that is) seems to be more an issue with entities... specifically mobs that have path-finding issues...

I can't guarantee that those really are the issues since it's fairly hard to tell by that Pastebin file... Someone with more experience has to look at this.

**Comment by lucko** [comment]
Seems like a corrupt database file, maybe?

Does it crash every time the server starts, or has this only happened once?
