### ISSUE TITLE
MySQL Connection Issues

### ISSUE THREAD

**Issue by SilverSleet645** [lucko/LuckPerms#1725]
Hi, I have been trying to get luckperms to connect to mysql. However, it never works, and just says there is a database error. I have checked the details several times, and even tried different hosts, but nothing works, and it is the same error every time.

Console error: https://pastebin.com/ZAMTeRj8
Version: v4.4.30

Thanks for reading
 - SilverSleet645

**Comment by Andre601** [comment]
What server type and version are you running?

The first error is not a MySQL/connection error:
`03.09 03:40:55 [Server] INFO java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/spi/ExtendedLogger;`

It can't find the Log4J logger which LuckPerms uses for the console. This could perhaps be caused by an outdated server version or not supported server type (e.g. CraftBukkit)

**Comment by Tobi406** [comment]
It could also be the same issue as in #1540.

**Comment by SilverSleet645** [comment]
Im running Spigot 1.8.8. I have also tried deleting the libs folder, but that didnt work either. Should I try a different version of 1.8.8? Like tacospigot or beerspigot?

**Comment by Andre601** [comment]
I recommend using PaperSpigot for performance improvements.
Also, on the issue Tobi linked does Luck respond with the following:
> This is most likely being caused by another plugin shading SLF4J incorrectly. Try running with only LuckPerms installed, if it works then you know the issue isn't being caused by LP.

**Comment by SilverSleet645** [comment]
I ran it on a local machine, and it worked first try! However, what is SLF4J and what other plugins use it? I have serverselectorx and ssx communicator on all servers. Could that be causing it?

**Comment by Andre601** [comment]
> However, what is SLF4J and what other plugins use it?

(From previous comment)
It can't find the Log4J logger which LuckPerms uses for the console. 

> I have serverselectorx and ssx communicator on all servers. Could that be causing it?

When the errors disappear when not using it, then yes.
Your best option is to add each plugin one at a time to your local test server to find the one causing it.
If for some reason none of the plugins causes those errors on your local server then perhaps it's an environmental issue caused by your server itself (Just a guess tho).

**Comment by SilverSleet645** [comment]
Im removing plugins from the server until the error disappears instead. Cause I have to clean up anyway. ill see what happens

**Comment by SilverSleet645** [comment]
Figured it out. Staff+ has some issues. Once i removed it everything started working perfectly.
