### ISSUE TITLE
Please help me I have been trying for WEEKS

### ISSUE THREAD

**Issue by Frityet** [lucko/LuckPerms#1773]
Im trying to make permissions for my minecraft survival server with friends and I JUST CANNOT find out how to make it so people joining can ONLY modifly the world (break, build craft) without having OP! I have the essentials 'tpa' working, but I cannot get this to work on ANY permissions? Please help. I do not know the command

**Comment by Andre601** [comment]
Make sure it's not spawn protection (set it to 0 in the server.properties).
Also, if you use WorldGuard make sure that the flag "passthrough" is allowed for the region _\_global__ (default)

**Comment by JavaCalorious** [comment]
LuckPerms command is /lp.
Make a group first by /lp creategroup <GROUPNAME>
Now if you want a prefix on it: /lp group <GROUPNAME> meta setprefix 1 "<PREFIX W/COLORS> (colour of name)"

Before we start permissions, can you list down all of the plugins of your server? (/pl in game to view)

**Comment by Frityet** [comment]
The plugins I currently have installed are:
dynmap, LuckPerms, WorldEdit, OmNom, AdminFun, Timber, BackpacksRemastered, Vault, WorldGuard, GUIShop, AreaShop, Essentials, GCore, Towny, Jobs, MCJukebox, GriefPrevention, CustomCommands, TownyChat, DiscordSRV, TownyNameUpdater, TheNewEconomy

**Comment by JavaCalorious** [comment]
**World Modification**

WorldGuard may already have its settings set, however, GriefPrevention is another plugin that is probably blocking every single modification to the world. GriefPrevention is like what it says, meant to block griefers, but for running a Survival server with claim blocks, it's better that you get a Survival plugin or a plugin that features claim blocks and buying of claim blocks using in-game economy (Essentials). If you really want to use GriefPrevention for setting up your server, you can follow the page on GriefPrevention [Setup and Configuration](https://dev.bukkit.org/projects/grief-prevention/pages/setup-and-configuration) which will help you to create admin areas that griefers cannot break and other things.

WorldGuard, like what Andre601 said, make sure that the flag passthrough is allowed for the region __global__ . You can do this by using this command: /rg flag __global__ passthrough allow. You may also use this command if you want players to be able to use items such as doors, trapdoors, jukeboxes, note blocks: /rg flag __global__ use allow. This should be it for WorldGuard. Make sure to copy the same exact region: its  _ _ global _ _ not _ global _.

**Permissions**

Setting up Permissions on LuckPerms is quite easy. I've been on a server with over 60 plugins, it's hard to configure, but there's a convenient way to do it with LuckPerms. Go into your game and type /lp editor. This will generate a link that will open up a Permission Web Editor. This will allow you to view your groups that you added and the permissions inside each group.

Now, you aren't familiar with the plugins' permissions. Of course I'm not either, but the internet has lists that you can follow for each plugin's command you are looking for. For example, you want to find the Essentials Fix command. You can go online and search "Essentials permission nodes" and there will be websites with the list. Use CTRL + F on Google Chrome to find the command and its node quicker.

Back to LuckPerms Editor, the Editor is there, once you find the permission node, go back to the editor, find the group you want to apply the permission to, and you will probably be seeing a ton of different things and a '+' sign.

![image](https://user-images.githubusercontent.com/40225169/66300879-a9e79180-e928-11e9-9452-297ea3d63fba.png)

Permission: Put your permission node here and remove any unnecessary spaces
Expiry: If you only want the permission to last for a period of time, you may fill this up, otherwise, leave it blank
Server: Leave this blank
World: If you only want it to apply to a single world, fill this up, leave blank for all the worlds.
Contexts: This is unneeded, leave it blank
True - When pressed, it will turn to false. This is the same as adding a positive permission or negating a permission from a group. If its true and you add it, the group/user will be able to access this command. If its false, the player will not be able to.
When you have done all the configuring of the permission you want, press the + sign and it will be added to the list below the blank spaces.

When you are done adding permissions from the editor, press the floppy disk "SAVE" icon and it will load up a command. Copy that command by pressing on it or using CTRL + C, and paste the command in Minecraft using CTRL + V. And run the command, you will be spammed with a few things, but those are the changes that will be applied.
**Reminder: Don't use the same editor everytime you are editing permissions, or else the permissions will mess up and may duplicate in some cases.**

The more easier way but makes life tougher is using the ingame command to add permissions:
/lp group <GROUP> permission set (permission node) (true/false)
The same applies for players, just change "group" to "user".

When you are ready, go ahead and give your players their ranks. Use
/lp user <Player> parent set <Group>
and there you go.

**This may be long, but its what's essential for LuckPerms and your problem, my explanations also**

Good Luck handling your server!

**Comment by Frityet** [comment]
Thanks! ill try right now

**Comment by JavaCalorious** [comment]
Did it work? You may mark this issue as closed when done.
