### ISSUE TITLE
Ultra Permissions migration support

### ISSUE THREAD

**Issue by ghost** [lucko/LuckPerms#1811]
Hello, my name is Raimu. I am a staff for the TechsCode team, and am reaching out to you on behalf of the importing of data from Ultra Permissions. Tech has decided to add Ultra Permissions as a resource to your SpigotMC account. It should appear under "Purchased Resources". If you have any issues, please feel free to contact me in this issue or in your server by tagging "@ mega floof#5684".

**Comment by electronicboy** [comment]
That is likely useless given the open-source nature of LP, building of the plugin requires that dependencies, etc; are available, which without publishing on a maven repo would create some headaches for anybody wanting to compile the plugin without those dependencies; I'd imagine that if you wanted to help with this properly, you'd need to actually release a public API depedency so that LP and other plugins can actually compile against the API of UP

**Comment by lucko** [comment]
Yeah, gonna be tricky to implement without their API being publicly (& I guess freely?) available.

**Comment by lucko** [comment]
https://github.com/LuckPerms/migration/commit/9efb876c8c6cf7c720cd4d3bf4ebf480fc7ed0b8
