### ISSUE TITLE
Config.yml default-assignments Problem

### ISSUE THREAD

**Issue by successed** [lucko/LuckPerms#1902]
This my config and this not work;

default-assignments:
  my-defaults-rule:
    if:
      has-true: <group.default>
    take:
      - group.default
    give:
      - group.oyuncu
    set-primary-group: oyuncu

Because, my server new member is not set oyuncu group;
![Screenshot_1](https://user-images.githubusercontent.com/13768414/71554852-d1d12780-2a35-11ea-9909-6de835525cb4.jpg)

Server version : 1.14.4-Paper #237
Luckperm version : 5.0.39

**Comment by BrainStone** [comment]
Don’t just ask on the Discord and here. 

For other people coming across this: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5

**Comment by Andre601** [comment]
[default-assignment]: https://github.com/lucko/LuckPerms/wiki/Extensions#extension-default-assignments
[legacy-extension]: https://github.com/lucko/LuckPerms/wiki/Extensions#extension-legacy-api
[update]: https://github.com/lucko/LuckPerms/wiki/Upgrading-from-v4-to-v5
[default-groups]: https://github.com/lucko/LuckPerms/wiki/Default-Groups

# Common v5 issues

## Plugin x spams errors about LuckPerms
If the error contains `Caused by: java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms` then the plugin uses the old v4 API of LuckPerms, while you're using LuckPerms v5.
A solution to this problem is to [download and install the legacy-API extension][legacy-extension] into the `extension` folder located inside the `LuckPerms` folder. If no such folder exist, create it.
Also, please contact the developer of the plugin and ask them to update to the latest release of the LuckPerms API.

If the error however contains `Caused by: java.lang.ClassNotFoundException: net.luckperms.api.LuckPerms` then it is the exact opposite and you're using LuckPerms v4 while the plugin is using LuckPerms v5.
In that case, do you need to update LuckPerms to v5. A page explaining how to migrate from v4 to v5 can be found [here][update].

## The expansion for PlaceholderAPI/MVdWPlaceholderAPI doesn't work
Please refer to the above section for how to solve this.
Just note that the latest version of the expansion is only compatible with LuckPerms v5.

## Default assignments don't work
The default assignments got removed in LuckPerms v5.
A temporary solution is to [download and install the default-assignment exptension][default-assignment] into the `extension` folder located inside the `LuckPerms` folder. If this folder doesn't exist, create it.

This, however, should be treated as a temporary solution and you should switch to an [alternative method][default-groups] instead.

**Comment by successed** [comment]
Okay t,y guys.
