### ISSUE TITLE
User data

### ISSUE THREAD

**Issue by falken91** [lucko/LuckPerms#1943]
Hi I'm using luckperms in my spigot server 1.15.1 and I save all the data as YAML format. My problem is that user folder don't add user data unless I gave them a rank, like admin or stuff. By the way, if I check user data on the server for default user, the information is correct but don't generate the file.

Sorry about my english, I'm from Argentina, greetings.

**Comment by Andre601** [comment]
This is intentional.
LP doesn't save any user-information if they only have the default group assigned. This was made to keep storage space low as you don't need to save a user that only has the default group.

We also recommend to __not__ edit groups and users manually through the yaml files.
Use the web editor instead.

**Comment by falken91** [comment]
Oh thanks for the quick reply! It's clear now!
