### ISSUE TITLE
Group Change Messages

### ISSUE THREAD

**Issue by Jaimss** [lucko/LuckPerms#1944]
Would it be possible to get some messages for players when their group changes so they know their group has been updated? I made a fork of this repository so I could edit the config, which is found here: https://github.com/Jaimss/LuckPerms/blob/master/bungee/src/main/resources/config.yml
Essentially I added this to the Extra Settings Section:
![image](https://user-images.githubusercontent.com/53633325/72740817-739aee80-3b74-11ea-928b-86750517c51b.png)
In this example, the {new} and {old} placeholders would represent the ranks that people had and received, and they would hopefully show the formatting that was given to them with /lp group {group} setdisplayname
The groups that will be notified section should be the groups that get notifications sent to them. Essentially if I get added to the VIP group, it should check that list for VIP and then decide if I get notified or not.

I also don't know how it would work out with Bungee / Spigot / Others, but at least for bungee, it would be great if it would send it to all servers, so if I change someone's group from the hub, and they are on Skyblock, they still get notified. 

If I forgot any of the important parent commands please reply to this issue with those.

**Comment by Andre601** [comment]
This was requested before and was denied, because it is out of scope for a permission plugin.
It is the job of other plugins to inform a player if they retrieved a role (e.g. for donating).

And due to the nature of LP in terms of [how translations work]() would this also be not quite useful.
This is something only a few people requested so far and nothing that imo should be added as the majority doesn't want this.

**Comment by Jaimss** [comment]
Ok, thank you. I'll close this issue then.
