### ISSUE TITLE
Command for Rank

### ISSUE THREAD

**Issue by R4zzerYT** [lucko/LuckPerms#1958]
Hey! I have a question. I want to have a system on my server to give active players new ranks. So, how can i give them a role, without replacing the previous rank?

I mean, players with the "default" role get an "upgrade" to "Iron".
Thats working.

But when my team reach the required onlinetime, they get the "Iron"-Rank and this rank is displayed.

Can i sort ranks with priority or something like this?

**Comment by Andre601** [comment]
Displaying what rank is shown depends on many factors like if a group inherits from another one, if it has specific prefixes/suffixes set, what the weight is, etc.

We can't really give you a solution because we don't know your setup yet. Do you use tracks? Do the groups have weights? Does iron inherit from default or other groups? etc, etc, etc.

**Comment by lucko** [comment]
It sounds like tracks is what you're after.

https://github.com/lucko/LuckPerms/wiki/Tracks
