### ISSUE TITLE
Suggestion: make developer API backwards compatible

### ISSUE THREAD

**Issue by Eufranio** [lucko/LuckPerms#196]
The LuckPerms Developer API is changing a lot. My suggestion is to make the methods backward compatible, so you don't remove the methods, and instead add a message in the console, like:

[LuckPerms] The plugin **MagiChat** is using the method **me.lucko.luckperms.api.Group.getAllNodes** was removed in newer versions of LuckPerms. Please report it to the plugin author.

That would plugins to not break on every LP update 😄

**Comment by lucko** [comment]
"The LuckPerms Developer API is changing a lot" - Are you kidding me? There has been **one** backwards compatible change since it was first released.

I also documented it this change very clearly, and gave specific wanting about which methods were removed.
https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/update?update=145645
https://gist.github.com/lucko/fdf6ae4b2d9e466d8103dd9c68e5db9e
https://github.com/lucko/LuckPerms/wiki/Developer-API#versioning

I suggest you read up on Semantic Versioning. LuckPerms follows it.
http://semver.org/

The version bumping to 3.0.0 is enough to tell you there were backwards incompatible changes in that release.

"That would plugins to not break on every LP update 😄"
You clearly have no clue what you're talking about.
