### ISSUE TITLE
Chat setPrefix not working in 1.12.2

### ISSUE THREAD

**Issue by Cleardragonf** [lucko/LuckPerms#1962]
I get no Error message in console...and everything Seeems to work...but no when i sync..the updates for the suffix don't take place in the game.

**Comment by Andre601** [comment]
Your issue lacks information for us to actually help you solving it.
Please provide information like:
- Steps you took
- Your current configurations of LP (Share through https://hasteb.in and make sure to remove sensitive information like passwords)
- What is your server type?
- What other plugins do you use?

**Comment by Cleardragonf** [comment]
•  /lp group default meta setprefix 100 &G[Player] followed after it said it set it to the context of global...i did /lp sync...logged out of minecraft and logged back in..still no change
•  current version: 5.0.39
•  Server type: Sponge Forge 1.12.2
•  No other plugin.

**Comment by Andre601** [comment]
Your issue is, that LP does not manage the chat whatsoever... You need a separate plugin for managing the chat (Nucleus is recommended for Sponge servers).
You can check if LP did its job, when the prefix is showing for a player when using `/lp user <user> info`

Also, if you're using a normal server and not a server network, then the sync command is pointless as it is meant to be used on server networks and not normal servers.

**Comment by Cleardragonf** [comment]
aah thanks
