### ISSUE TITLE
Renaming default

### ISSUE THREAD

**Issue by Sigalax** [lucko/LuckPerms#1981]
I cannot rename default. I tried doing /lp group default rename member. It works temporarily but eventually, member is another existing rank and default is still there. Every time I tried reloading through the server, loading through luckperms, or restarting the server, it won't work.

**Comment by Andre601** [comment]
This is because you're not supposed to rename it.
LuckPerms always has a group called default, since that's the group everyone gets.

You have a few options to change the behaviour of default. You can either change the display name (It's still called default in LP but will display the other name for every plugin that gets it through Vault) or edit inheritance.

More Info:
https://github.com/lucko/LuckPerms/wiki/Default-Groups
