### ISSUE TITLE
[Spongeforge 1.12.2][LP 5] Users can promote/demote themselves to highest rank, but adding arguement check permission nodes do not make a difference

### ISSUE THREAD

**Issue by FinalKill9175** [lucko/LuckPerms#1984]
Still not working. My server has one track named default and even when I add luckperms.user.promote.[track].<old/new-group> it does not let me execute the command. And I do have the option enabled in the config.
My default track goes default--->member--->trusted---->moderator--->admin---->owner
I want it so that the user inheriting trusted or higher can promote/demote players up to the group below them.
 i.e. for moderator, I put, luckperms.user.promote.default.trusted, luckperms.user.demote.default.member, and for trusted I put luckperms.user.promote.default.member, luckperms.user.demote.default.default, 
When I add the luckperms.user.promote/demote nodes to any group, they can still promote all the way up to owner, and when I take the main luckperms.user.promote/demote off, they can't even run the command at all.
I just want the equivalent of essentials.membership.manage.<group-name>
maybe add /promote [user] [track] and /demote [user] [track] commands?
edit: I followed the tutorial posted here: https://github.com/lucko/LuckPerms/wiki/Argument-based-command-permissions#checks-when-a-player-makes-changes-with-a-set-of-specific-arguments

**Comment by BrainStone** [comment]
There's a caveat on Sponge that's very easy to miss:  
The permission ``xxx`` also adds all permissions that start with ``xxx.``.  
That's why when you add the node ``luckperms.user.promote`` you also add all other nodes that start with ``luckperms.user.promote``, like ``luckperms.user.promote.default.default``.  
The way around this (or if you only want one node and no child nodes on Sponge) is by setting the node you want (`xxx`) to true and ``xxx.*`` to false. Then only ``xxx`` is true. If you later also set ``xxx.yyy`` it will be true regardless.

I hope that made sense to you.  
And my apologies for my late reply. I was fairly busy.

**Comment by FinalKill9175** [comment]
Thank you for getting back! I will give this a try and let you know.
