### ISSUE TITLE
[feature request] Auto Update Check

### ISSUE THREAD

**Issue by Pix-00** [lucko/LuckPerms#1990]
Its may be hard to add a function that can automatically fetch and download a newer version of LuckPerms. But, a small note to say that whether there is a newer version of LuckPerms will be very nice.

Hope it will not cause may troubles.

**Comment by lucko** [comment]
An auto updater is not something I want to add - I personally think that's much better being a manual process.

Update notifications is something I have considered, but feel that they're a bad idea for two reasons.

1. The project has new "development" versions released quite frequently - it's would be impractical to update for each release.
2. Most of the "development release" updates are not critical to the operation of the plugin - it's fine to just track the latest "stable" / "released" build on Spigot/Sponge/whatever, unless you encounter an issue which has been fixed in a newer version.
