### ISSUE TITLE
UUID bug on Bungeecord Servers

### ISSUE THREAD

**Issue by VollesHoeschen** [lucko/LuckPerms#2045]
Hey Guys,
I already had this bug with PermissionsEX and thought it would work with LuckPerms, but it doesn't.
So if I give myself the Admin Rank I've got in on the Lobby-UUID only and not on the other Servers like CityBuild. I know you can fix that problem with RedisBungee, but I wanted to ask if there's another option (a free one).

**Comment by electronicboy** [comment]
This sounds more like a request for support which would be far more suited for the discord

**Comment by Andre601** [comment]
Check that you actually setup BungeeCord properly, as in enabling `bungeecord` in the spigot.yml on all servers and enabling `ip-forwarding` in the config.yml of the BungeeCord.
Servers, that aren't setup properly will create and use their own UUIDs based on the name of the player, rather than using the one provided through ip-forwarding, as this is how Offline-mode servers work.

**Comment by VollesHoeschen** [comment]
ah thanks :dagger:

**Comment by VollesHoeschen** [comment]
Thank you so much <3
