### ISSUE TITLE
Plugin commands showing to all players

### ISSUE THREAD

**Issue by Federe76** [lucko/LuckPerms#2064]
I'm sorry, this might not be specifically a LuckPerms issue, but I do need help.

Issue: Players are shown suggestions for commands they don't have permissions for. When they start typing "/", they get 3 suggestions for all plugins. I'd like to know how I can make it so players are only shown suggestions for commands they are able to use.

Running Paper 1.15.2
Thanks in advance.

![image](https://user-images.githubusercontent.com/62208477/76703899-f8594300-66b3-11ea-9188-3ccd3a9076ef.png)

**Comment by Andre601** [comment]
This is - as you mentioned - not related to LP.
The issue is, that the plugins themself don't properly handle the commands (e.g. assigning a permission to the command through the plugin's plugin.yml) or similar.
A relatively *good* plugin would hide the command, when you lack the permission, which is a bit rare tho.
A solution for this would be to use a plugin that blocks the command suggestions if you lack permissions.
I can't suggest any specific one, but I'm sure a quick Google search can help you ;)
