### ISSUE TITLE
Luckperms is conflicting with tab plugin

### ISSUE THREAD

**Issue by ThePixelated1** [lucko/LuckPerms#2103]
I have an issue with LuckPerms overriding a different plugin i use to configure the tab.
The plugin i use for this is [https://www.spigotmc.org/resources/tab-1-5-x-1-15-x-free-version.57806/]
I have configured this plugin to order online players in the tab list (with higher ranked players nearer the top) and to format player names and their prefixes (They are formatted slightly differently to the prefixes they have in LuckPerms). However with LuckPerms, this config is totally ignored and lists the players in alphabetical order and uses the LuckPerms display names, instead of the ones from the tab plugin. I've looked through LuckPerms config for a while and can't find anything i think would change it. I googled around and found a thread from someone with the same issue but it was from 2 years ago and their config looks very different to mine.
Any help would be appreciated, Thanks!

**Comment by Andre601** [comment]
LuckPerms does not "override" another plugin.
It doesn't manage the tab list at all. This is all handled by the tab plugin and not LP. If you have issues with the tab list, then the plugin might conflict with another one, or it just sucks tbh.

Anyway, this is not an LP issue at all and entirely caused by the tab plugin itself.
I suggest requesting support from the dev of Tab here: https://discord.gg/EaSvdk6

**Comment by lucko** [comment]
LP doesn't touch the tab list :)
