### ISSUE TITLE
[Feature Request] Disable auto permission organizing.

### ISSUE THREAD

**Issue by Kyrobi** [lucko/LuckPerms#2106]
I don't know what it's called, so I'll just refer to it as "auto permissions organizing".

The request adds a config option to leave comments in flatfile groups without the plugin removing them. 

Example:

![image](https://user-images.githubusercontent.com/20980266/77731819-af698e80-6fd1-11ea-9e16-5ac16f76d2d8.png)

It helps when organizing permissions for each plugin when directly editing the files. Keeps the permission nodes for a group nice and tidy.

Currently, the plugin just alphabetize the perms: 
![image](https://user-images.githubusercontent.com/20980266/77732262-75e55300-6fd2-11ea-9ee7-ddf427c6259a.png)

It's nice, but I don't want my comments to be removed stating which plugin these permissions are coming from.

**Comment by Andre601** [comment]
It's not recommendet to set permissions directly through files, since there are better alternatives like the web editor.
In addition do file storages artificially increase storage space used.

**Comment by BrainStone** [comment]
The files only get reorganized when you change the permissions of what the file referrs to. So if you don't want it overriden, don't change the data through any means but the files.

Though I'd highly urge you not to do that. I mean to what plugin a permission belongs should be clear from the get go, as they start with the plugin name.

**Comment by Kyrobi** [comment]
Yes, I understand that commenting artificially increases the file of the file.

Regards to the permissions starting with the name of the plugin, yeah I get it. It sounds like a personal problem. But, it does make it looks nicer :D

**Comment by Andre601** [comment]
I talk about the files themself and not if the comments increase storage used.
Compared to H2 or MySQL are file-based storages much heavier in terms of storage used.

I don't think this will ever be added, as you're so far the only one suggesting it and we also recommend using alternatives, rather than editing the files directly.

**Comment by BrainStone** [comment]
The main issue with this request boils down to:
- The currently used YAML library doesn’t allow for persistent comments. As it’s the library shipped by Bukkit, it would require shipping a custom one, which comes within many problems. 
- It’s a personal problem, as you mentioned. And due to the previous point the effort required to implement this minute feature is several hours. Which is just not proportional to the benefit that feature would provide.

**Comment by Kyrobi** [comment]
Understood. Thanks!
