### ISSUE TITLE
LuckPerms-Bungee Crash/PermissionCheckEvent

### ISSUE THREAD

**Issue by FisherGee** [lucko/LuckPerms#2107]
My server runs fine for a few hours, however; after those few hours we start to get some errors. Eventually after a while it crashes. 

Here's the errors: https://pastebin.com/yMShTZXn

**Comment by FisherGee** [comment]
https://pastebin.com/1qa7gB9V
Here's another one. Could someone please help?

**Comment by Laarryy** [comment]
A few questions:
Are you running a cracked server?
Are you running a server network with Bungee?
    If so, what database and messaging service have you set up?

Feel free to [respond on the discord](https://discord.gg/luckperms), just let us know who you are and be ready to link this page!

**Comment by FisherGee** [comment]
> A few questions:
> Are you running a cracked server?
> Are you running a server network with Bungee?
> If so, what database and messaging service have you set up?
> 
> Feel free to [respond on the discord](https://discord.gg/luckperms), just let us know who you are and be ready to link this page!

Are you running a cracked server? No
Are you running a server network with Bungee? Yes those are from the Bungee
If so, what database and messaging service have you set up? MySQL/phpMyAdmin

I already tried contacting on discord and I was directed here. Could you maybe speak to me personally on discord? Riley#2020

**Comment by lucko** [comment]
The exception messages posted above are triggered when a plugin checks for a permission on a player which LuckPerms doesn't have any loaded data for.

This can occur:

1. When other plugins alter UUIDs during or sometime after the login process
2. When other plugins check for permissions after a player disconnects from the proxy
3. If due to some bug, LuckPerms unloads data for a user prematurely, or doesn't load any data in the first place.

However, the errors above don't give much of an indication as to which of these it is.

The whole proxy *crashing* is different to those exceptions being printed - I'd need to see the crash log to comment further on that.

You full log file might prove more useful in finding the issue.

**Comment by lucko** [comment]
I've also made the logging a little less verbose: c71742a996473d11582256133d935448f417099f

**Comment by BrainStone** [comment]
Good to know that BungeeChat is not the only plugin "causing" these errors. So @FisherGee I think it should be absolutely clear that it's not a BungeeChat issue.

**Comment by FisherGee** [comment]
> Good to know that BungeeChat is not the only plugin "causing" these errors. So @FisherGee I think it should be absolutely clear that it's not a BungeeChat issue.

I removed BungeeChat though and I haven’t seen any of those errors yet. I’ll keep you updated.

**Comment by BrainStone** [comment]
> Your full log file might prove more useful in finding the issue.

That's why Luck closed the issue btw.

**Comment by lucko** [comment]
I've made some commits to hopefully fix this.

Please test and let me know :)

**Comment by FisherGee** [comment]
> I've made some commits to hopefully fix this.
> 
> Please test and let me know :)

Thanks, however; we just removed BungeeChat and that seemed to do the trick.

**Comment by lucko** [comment]
Apparently it's fixed soooo, gonna close.
