### ISSUE TITLE
World Guard entery denial interfears with the group.<group>

### ISSUE THREAD

**Issue by Viagrin** [lucko/LuckPerms#2108]
Hello Today I switched from Permissionsex to LuckPerms and I must say I love it, but I crossed by to a problem.
I used this method to allow cerian groups to enter a specific area protected with world guard:
_

> /region flag Stuff entry deny
> /region addmember Stuff g:CoolPeople
> /region flag Stuff entry -g nonmembers
> 
> Then I'd add the permission node "group.CoolPeople" to the CoolPeople group in your permissions plugin's config.
full thread [click here](https://bukkit.org/threads/how-to-use-the-entry-group-flag-in-worldguard.124066/)
_

and the problem is for example i have a region only for vips and the permission node is group.vip to enter it messes up the inheritance of the permissions for the mvp group or the region entry denial doesn't work

if there is a way to fix this please tell me.

**Comment by Andre601** [comment]
Groups are lowercase and not uppercase.

**Comment by lucko** [comment]
LuckPerms internally uses the `group.<group name>` permission to denote group membership.

So for example, it's not possible to give `user x` the `group.admin` permission, without automatically making them a member of the `admin` group.

My suggestion for solving your issue is to just add all of the LP groups you want to access a region to the definition in WorldGuard.

e.g.
```
/region addmember Stuff g:vip
/region addmember Stuff g:mvp
... etc
```
