### ISSUE TITLE
I have a target problem

### ISSUE THREAD

**Issue by xMeme7** [lucko/LuckPerms#2125]
I'm trying to make a skyblock in which the improvements of the island are unlocked with money, but when I enter the command that through npc it will go to console ie "/ lpb user %player% permission set askyblock.island.range.150" or something like that instead of% player% I tried with "@p" etc but it turns out that the command doesn't exist, is there any way to do it?

**Comment by Andre601** [comment]
Citizens is a **Spigot** plugin, therefore handling commands on the Spigot server/Console.
`/lpb` is the command of LuckPerms **Bungee**, a BungeeCord plugin.
BungeeCord and Spigot are two completely separate things and won't interact with each other, except for some really specific cases.
Just use the Spigot version of LP and use `/lp` instead of `/lpb`
In addition is it not LPs job to translate placeholders in commands, that would be Citizens job.
