### ISSUE TITLE
addtemp for permission

### ISSUE THREAD

**Issue by bonjourkemal** [lucko/LuckPerms#2133]
why does not it have "/lp user %user% permission **addtemp** %time%"?
I really need to this.. Please add addtemp for permission to lp into commands. i will not use code blocks like.

**Comment by Turbotailz** [comment]
Someone hasn't read the wiki...

**Comment by Laarryy** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp-node-truefalse-duration-temporary-modifier-context

**Comment by Laarryy** [comment]
Read the wiki next time.

**Comment by Turbotailz** [comment]
https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Permission#lp-usergroup-usergroup-permission-settemp-node-truefalse-duration-temporary-modifier-context

**Comment by bonjourkemal** [comment]
I already know **settemp** but i said **addtemp**. so we give the ability to fly 30 minutes when the player scores the first vote, but I want to add 30 minutes on top of the second vote. So "settemp" is not what I want. "Addtemp" I need.

**Comment by bonjourkemal** [comment]
Even when I try it, it warns "There is already."

**Comment by Laarryy** [comment]
[https://i.imgur.com/ZIKr6Le.png](https://i.imgur.com/ZIKr6Le.png)

On the wiki, in that section, the one you were linked to twice, there is a section where modifier keys are explained. The temporary modifier [accumulate] can be added onto the end of the command to make it add up instead of reset. Additionally you can also set the default for settemp commands in the LP config to always accumulate without the specification in the temporary modifier.

Again, this is in the *same section* that you were linked to, twice. Actually reading it instead of skipping it or skimming it would really have helped you out here.

**Comment by bonjourkemal** [comment]
Yes, I missed it. The reason for this is that my English is weak. I want amnesty from you. If possible, can you delete the topic I opened?

**Comment by Laarryy** [comment]
I can't, don't have the ability to. It's all fine by me, though, just don't be so aggressive in a request for a feature, especially one LP already has.
