### ISSUE TITLE
Avatars in web editor are all Steve on a non-premium server.

### ISSUE THREAD

**Issue by workonfire** [lucko/LuckPerms#2176]
Hey, I would really like to see my users' avatars in the web editor (`/lp editor`).
However, my server is non-premium and every player head on the list appear as Steve.

I suggest retrieving the Minotar skull not using an **UUID**, but the **username** instead.
This requires changing the URL from for example
`https://minotar.net/helm/17257402-4aa4-36f4-adf4-c0fff91b8b7a/100.png`
to `https://minotar.net/helm/nickname/100.png`.

![image](https://user-images.githubusercontent.com/34654573/79222626-2f0fae00-7e58-11ea-9cf2-25dc5eb1abea.png) **_>>>_** ![image](https://user-images.githubusercontent.com/34654573/79222635-333bcb80-7e58-11ea-8849-66c1a5f0c1a6.png)

**Comment by codingJWilliams** [comment]
Retrieving avatars by username is deprecated, due to a) the Mojang ratelimits, and b) the fact that UUIDs are the recommended way to refer to specific accounts.

Offline mode players do not have real skins - that skin you posted is not in fact the skin off the offline player `buty935`, it is the skin of the real online mode premium player in question - therefore it would not make sense to display skins for them.

It is possible to fork & self host the editor if you wish to change this behaviour.

**Comment by Andre601** [comment]
As mentioned by @codingJWilliams are username-lookups deprecated and most APIs to retrieve a players avatar/skin have removed such a support (with some exceptions).

The fact that your server is in cracked (offline) mode comes with such disadvantages, as the server itself wouldn't lookup the skin of a player either. You can simply check your tab list to see this effect in action.
On offline servers do tab lists not show the face of a player, while they do on online mode servers.

Your suggestion would imo not provide any useful improvements towards the web editor and would only make things more unreliable.

**Comment by workonfire** [comment]
Thanks. I had no idea this would be such a problem.
