### ISSUE TITLE
100% Messages Configurable

### ISSUE THREAD

**Issue by NeptunePlayz** [lucko/LuckPerms#2190]
As you can see http://prntscr.com/s13l5u, the commands are green and where it says Running v"version", it's the default colors, these are unchangeable...

**Comment by lucko** [comment]
Yeah these messages aren't configurable - the name of the plugin & the version aren't locale dependant.

**Comment by Martin-Hausleitner** [comment]
but i dont want that a player see that so pls add a perm

**Comment by BrainStone** [comment]
Why?

What are you getting out of hiding your permissions plugin?

**Comment by Andre601** [comment]
You kind of insult every developer by hiding the plugin name (and version) from others.
Some if not most devs do work on those plugins in their free time, which often also costs money for them (Hosting own CI servers, licenses and such stuff)
Not everyone donates to the dev to support them and this kind of exposure is the most they often get.
So hiding what plugin you use and who made really takes away the small expose some devs often have.

It also isn't that big of a deal. What would showing the plugin name cause to you? If everything is setup should it be safe to use and there shouldn't be any exploits or similar.

**Comment by Martin-Hausleitner** [comment]
I want a professional Server

**Comment by Martin-Hausleitner** [comment]
And there a server hoster to support luckperms

**Comment by BrainStone** [comment]
Hiding plugins achieves 0% of that.

I know plenty of professional servers that don't even block ``/plugins``.  
Plugins and how you configure/hide them is not how you make your server professional. It's the time and effort you put into the server itself. The concept, the game play, the worlds/maps, etc. etc. etc.

**Comment by Martin-Hausleitner** [comment]
Mhh it is professional lock if no one know any plugin that is a ideal server

**Comment by Andre601** [comment]
Answer me one question then:
What about hiding a popular plugin's name makes your server more *professional*?

Your point makes no valid sense and I refer to my previous post: Hiding what plugin is used and who made it is basically insulting the dev.
LP isn't that small I know. But some plugins are and this kind of exposure is often the only method a developer has to share his plugin.

And wow.... a host.... You are aware that hosts not always give money or similar in return, right? They either give a discount on their products for the partner, or in some cases even nothing.
Also, not everyone wants to have a Sponsor, because this often comes with certain requirements and obligations to do, which some wouldn't like.

The point is, that hiding plugins is in no way professional. Don't come with the "But servers like Hypixel do it" crap as you should never take gigantic servers as role models, because this is the wrong approach.
Your server is in no way professional if it uses already existing plugins and is yet another SkyBlock server with creative and Prison Mines.

**Comment by BrainStone** [comment]
I've written a post on that exact topic a while back: https://mcserverrant.weebly.com/rants/why-you-shouldnt-hide-your-plugins
