### ISSUE TITLE
Failed to init storage implementation

### ISSUE THREAD

**Issue by MisterToasty** [lucko/LuckPerms#2231]
Password to my mongodb is nothing, and username is root. The port is not exposed outside of localhost

the error is:
https://pastebin.com/K31v8PA5

**Comment by Andre601** [comment]
I can see multiple issues here
1. Not having a password is bad practice and should be avoided. Always set a password, so that you have some protection agains people accessing the database.
    - This is also the main cause of the issue, as it seems that the password can't be null/empty
2. **Don't** use root. This user is only meant for you (the administrator) and shouldn't be used by plugins at all. Reason behind this is, that root can access all databases, so a malicious plugin could abuse this, or someone could take advantage of this.
Always create a separate user (with password) that only has access to specific databases. This reduces the risk of someone harming your database a lot.

**Comment by MisterToasty** [comment]
Fixed this by changing the user, thanks.
