### ISSUE TITLE
Prefix Stacking issue!

### ISSUE THREAD

**Issue by DuhGhost** [lucko/LuckPerms#2264]
Hello may someone please help me with prefix stacking for my server! I've tried using the 2 GitHub links that explain how to do it but for some reason it wont work! Thank you!

Like i go into the config and set the higest/lowest thing and it still wont give me 2 prefixes only 1

they spawn as the default group, then they get to choose between 3 classes, (so 3 classes are all the same just different names) and then im trying to add the donor group so it just shows their prefix and them inherit the permissions
So i want it to be {E} {Blash} {Player}:

(ps i tried to get help from the discord channel so this is what i sent) 

Here is my config https://pastebin.com/T80JTnQg
My editor https://editor.luckperms.net/1wHtHnacWk

**Comment by Laarryy** [comment]
Hi! 
One thing I'd try doing is putting the groups on tracks, even individual tracks, and using the `"highest_on_track_<track>"` formatting key. This may solve your problem quite easily. 

If that does not work, the editor session is outdated - would you mind sending a new one?

Finally, the way that you should check a user's prefix is not through chat, but using `lp user <user> info` because that will tell you what LP sees as the prefix, and sometimes the chat plugin is at fault. Thanks!
