### ISSUE TITLE
LP isn't registering perms correctly

### ISSUE THREAD

**Issue by Chazza** [lucko/LuckPerms#2321]
Hi,

Long story short, LP check command deems that players have permissions, but when they attempt to run commands or features through other plugins - its as if they don't actually have this permission.

For example, the permission `nte.moderator` is set to the group `default`, when running a check on a player I get the following:
```
[10:46:36 INFO]: [LP] Permission check result on user Gang for permission nte.moderator: true
```

Yet when this player joins, they aren't provided the tab prefix, this also stretches further to any other permission such as essentials.fly, players are provided with the no permission message.

Is there any chance you can implement a new check for this, even if its experimental via a toggle.

Thanks

**Comment by ProSl3nderMan** [comment]
I've also had a similar problem to this. My default group had essentials.fly, but Admin couldn't do /fly even though they inherited it from mod which inherits from helper which inherits from default. Important to note here that I am using a cross server setup. Since I was using a cross server setup, I had to specify for the parent to be context server=serverNameHere or they would not inherit the permissions from default group on that server.

I don't know if this is intentional or not in LuckPerms, but I wonder if this is the same problem you are having with a cross server setup. I urge you to check to see if this solves your problem **_if you are using a cross server setup_** (where LuckPerms shares the same database, and every server under a bungee proxy has separate permissions from each other using contexts for server=serverName).

**Comment by Laarryy** [comment]
@ProSl3nderMan there is a good chance you changed `include-global` in your LP config - if that's changed, contexts must be set for perms to apply

**Comment by ProSl3nderMan** [comment]
> 
> 
> @ProSl3nderMan there is a good chance you changed `include-global` in your LP config - if that's changed, contexts must be set for perms to apply
Assuming the default value is suppose to be **true**, I have not changed it, yet it stills requires me to apply the context.

**Comment by Laarryy** [comment]
Could you pastebin that config here, or even confirm for certains that it's not? Also, if you've changed the contexts file to add default contexts, then global will not be default, and you'd have to explicitly set another to apply

**Comment by ProSl3nderMan** [comment]
> 
> 
> Could you pastebin that config here, or even confirm for certains that it's not? Also, if you've changed the contexts file to add default contexts, then global will not be default, and you'd have to explicitly set another to apply

After further investigation, it was because of a group named member not inheriting default since another admin deleted it.. I apologize for the misinformation, everything said by me should be disregarded, other then the fact that if you are using cross-server permission setup, you should verify that include-global is properly setup for your configuration, set to true if you want all permissions inherited from global, or false for just the contexts regarding your server.

Thank you, @Laarryy .
