### ISSUE TITLE
Can OP's bypass negative permissions?

### ISSUE THREAD

**Issue by Zelkam** [lucko/LuckPerms#2428]
I want to add negative permissions, mainly bukkit permissions, to default rank, but at the same time I want OP's to have access to said permissions. Is there any way for OP's to simply bypass any and all negative permissions without having to give myself direct access to the permission.

**Comment by Turbotailz** [comment]
You could simply make the Ops not inherit the default group, though IMO that's not best practise.

There isn't really any way around it, you will most likely need to re-add the permission in a higher up group.

**Comment by BrainStone** [comment]
I mean why set negative permissions in the first place?  
The permissions should default to true in the first place.

**Comment by A248** [comment]
You may tend to prefer explicitness, as I do, of which default permissions is an enemy. In your configuration, disable default permissions. Now, regular users will not have these permissions. You can then grant permissions to other groups explicitly as you see fit.

**Comment by benwoo1110** [comment]
Since you want to grant permissions to other groups explicitly as you see fit, you can do the same for all players including admins. Moreover, almost all permissions nodes are default to false even without setting them, so you can just not set them at all in default group. (I think that was what BrainStone meant)

Allowing OP to bypass permissions kinda defeat the purpose of using a permission plugin to control perms. This will also lead to a case where OPs players inherit false perms but still allowed to do the commands, causing direct conflict with what LuckPerms job is as a permission manager.
