### ISSUE TITLE
Luckperms Slow

### ISSUE THREAD

**Issue by Ninjablader101** [lucko/LuckPerms#2437]
Luckperms is currently being slow I have tried a lot of things I have restarted the server. Restarted the bungee but it still remains to be slow. When I do /lp editor it takes about 30 seconds to load up a link or say anything. Or really any commands with luckperms.
Another thing is that if I give player permissions in bulk with a command it takes a while for them to load since it seems it loads one by one and not in bulk

**Comment by Ninjablader101** [comment]
> 19:10:57 [WARNING] [LuckPerms] Processing login for TenseJuice took 1924ms.

**Comment by A248** [comment]
LuckPerms interacts heavily with its database backend; if the database is slow to respond, it will hold up everything down the line. Your issue is most likely due to slow database connection.

If you are using a remote database such as MySQL, determine the distance between your MySQL database and your MC server. If they are quite far away, it may take a while for queries to travel back and forth. Further, if you are using a shared MySQL host, assess whether it might be overloaded on account of overselling.
