### ISSUE TITLE
My group (developer) and all other roles / groups are duplicating pls help

### ISSUE THREAD

**Issue by DupeJosh** [lucko/LuckPerms#2552]
Please help this one of the only things holding us back from opening to public

**Comment by DupeJosh** [comment]
![image](https://user-images.githubusercontent.com/69511250/89888892-a405b100-dbc8-11ea-8908-a08c23da59c1.png)

**Comment by BrainStone** [comment]
That is your chat plugin. You need to configure it properly. Reach out to their support if you need more help.

**Comment by DupeJosh** [comment]
we use LuckPerms Chat

**Comment by benwoo1110** [comment]
Then you should reach out to LuckPerms Chat as LuckPerms Chat plugin is not developed LuckPerms. 

LuckPerms is only able to send information to formatting plugins so that they display them properly. LuckPerms does not put the prefix in front of your name, you need a chat formatting plugin to do it, and you need Vault. Same goes for the tablist! If the information appears correctly when you run` /lp user <user> info`, LuckPerms is doing its job! ;)
