### ISSUE TITLE
Can't add prefixes/suffixes with a period from the web editor

### ISSUE THREAD

**Issue by Turbotailz** [lucko/LuckPerms#2568]
Try add a prefix in the web editor `prefix.100."test.prefix"` then apply the edits, the period will be escaped like `"test\.prefix"`

If you try to add the prefix in a command then it works fine `/lp group <group> meta setprefix 100 "test.prefix"` 

The data returned from the web editor does not include an escaped period.

**Comment by lucko** [comment]
![](https://i.imgur.com/0s0iLfT.png)
![](https://i.imgur.com/H7ursTw.png)
![](https://i.imgur.com/SpF0qZN.png)

Seems to be working as intended - the escaping is performed by LuckPerms on the plugin side, but it accepts input from the web editor in a non-escaped format too.

For prefixes it is not a big deal, since the weight section cannot contain a `.` anyway - it's more important for meta nodes...


* `meta.magic.property.yes` --> **key:** `magic`, **value:** `property.yes`
* `meta.magic\.property.yes` --> **key:** `magic.property`, **value:** `yes`
* `meta.magic.property\.yes` --> **key:** `magic`, **value:** `property.yes`
