### ISSUE TITLE
Commands.yml Issue

### ISSUE THREAD

**Issue by JessePesse123** [lucko/LuckPerms#2586]
Hello,

I tried to make a custom command/alias: **'/mpetgive (player) (permission of the pet'** wich outputs 2 things:
- A luckpermscommand wich gives the permission for the pet
-  A broadcastcommand wich broadcasts that the player has won a pet.
This is the output in chat: 
![2020-08-26_13 52 45](https://user-images.githubusercontent.com/66204768/91300523-b9233800-e7a3-11ea-837d-e1f36ae61701.png)

This is our command.yml configuration:
```
mpetgive:
  - luckperms:lp user $$1 permission set $$2 true server=global
  - broadcast &f$$1 won een &ampet &fIn zijn/haar crate!

```

Thank you already!

**Comment by Fefo6644** [comment]
Issue context [here](https://discordapp.com/channels/241667244927483904/690683905677983756/748137927783088269) (LP discord server).
Possibly related to [this](https://discordapp.com/channels/241667244927483904/308232296753004556/746852669460840468) (again LP discord server)? *If so* (which is probable since command blocks/command.yml parse the command through `CommandNode#parse` before executing), commodore/the commodore file parser could accept a token for end points/execution points to allow things like this.

**Comment by lucko** [comment]
Please try using LuckPerms `5.1.98` or newer, and set `register-command-list-data` to false in the LP `config.yml`.

**Comment by JessePesse123** [comment]
I'm on 5.1.98 and can't find  register-command-list-data in the config.yml?

**Comment by lucko** [comment]
Just add

```yml
register-command-list-data: false
```

to the bottom of the file :)

**Comment by JessePesse123** [comment]
It worked, thanks!

**Comment by lucko** [comment]
Great!
