### ISSUE TITLE
Option in the Config for Short-Time Permissions

### ISSUE THREAD

**Issue by Endphoenix** [lucko/LuckPerms#2609]
### Description

If someone has a Permission, but then gets it again for a short time by being assigned to a group for a short time, and then the group is removed from him after that time, then he no longer has the permission. 

### Proposed behaviour

An option in the Config. If you set it to "true" and then someone has a permission and gets it again by being assigned to a group, then he still have it after the time has elapsed. 

If the option is set to "false", everything is as it is now.

**Comment by BrainStone** [comment]
I don’t understand what you mean. 

Also be so kind and explain your use case.

**Comment by Endphoenix** [comment]
Oh, I'm only now finding out that you can't add someone to a group for a short time. This can only be done with Permissions. Then I just make an extra issue for it.

**Comment by Laarryy** [comment]
This is the temporary modifier value that you can add to the end of a permission so it accumulates on the time instead of replacing. I believe the table can be found here explaining what temporary modifiers do https://github.com/lucko/LuckPerms/wiki/Command-Usage:-Parent#lp-usergroup-usergroup-parent-addtemp-group-duration-temporary-modifier-context

**Comment by BrainStone** [comment]
You still haven't explained it any better, nor your use case.

Assigning a group to a player (temporary or not) never copies the permissions over.  
If you want a permission to persist, just assign it to the player directly.
