### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by Tenkomanker** [lucko/LuckPerms#2666]
I have luckperms installed on a sponge server for 1.12.2 and just installed nucleus to give more commands that I can use for myself and others like /tpa, /spawn, /home etc. After installing nucleus, the permissions for pixelmon disappeared from luckperms completely. Is there a way to re-display them?

**Comment by Turbotailz** [comment]
In what context do you mean they have disappeared? Re-display them where, how?

Need more info.

**Comment by Tenkomanker** [comment]
So, for example, when you open the editor and use the search bar at the bottom, it gives you a full list of permissions right? Before, the permissions for pixelmon and the other mods I have installed were "pixelmon.command.[]" or "wondertrade.command.[]" but now all that is there are nucleus commands.

**Comment by Turbotailz** [comment]
Right, so that list isn't actually a "full list of permissions", it's merely a list of suggestions based on what LuckPerms knows. There are certain reasons why permissions will be shown there:

- The permissions have been defined correctly within the plugin/mod (I actually have no idea about mods so can't say whether there is some sort of interface for defining permissions which is readable from a plugin like LP)
- The permissions have been checked since the server was last restarted - LP will cache checked permissions and send these to the web editor - it's highly possible that the permissions you usually see just haven't been checked since the last restart, so as a result they are not shown this time.

You could attempt to perform some permission checks for the missing nodes and see if that helps. Usually running something like `/help` will generate a ton of permission checks and might populate the list (again, no idea if this works for mods).

**Comment by Tenkomanker** [comment]
The issue also persists in-game as well. If I were to use tab to auto-complete, pixelmon and other mods don't show up as an option to set permissions for.

**Comment by Timmy109** [comment]
Did you read what Turbotailz sent?

**Comment by Tenkomanker** [comment]
Yea, I'm doing what he suggested to do with the `/help` command but it doesn't seem to be working. I'll restart the server and my own client and see if that fixes the issue

**Comment by Tenkomanker** [comment]
The `/help` command seems to have worked. Thanks!
