### ISSUE TITLE
One time commands [question]

### ISSUE THREAD

**Issue by TheDoctor025** [lucko/LuckPerms#2683]
Not an issue, just a question. Is there currently a way to add a one-time command? Not temporary permissions, but where a person gets access to a command to use it just once.

**Comment by Fefo6644** [comment]
Not really possible, permissions aren't bound to commands only, but plugins can check for a certain permission anytime, when moving around, doing certain actions, running *other* commands, __even when showing up command suggestions while typing them in chat!__
While this at first seems like (and would be) a great idea at first, it isn't really possible due to the nature of "permissions are not always for commands, they can be checked at all times".

**Comment by TheDoctor025** [comment]
Thanks for the response. Should I understand, then, that the only way to implement this on a server would be to integrate this functionality into the plugin that manages the command?

**Comment by Fefo6644** [comment]
Correct, it would be up to the plugin author to implement such feature, as they are the only ones that can fully control when the action is completed successfully.

**Comment by TheDoctor025** [comment]
Alright, thanks.
