### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by bloodmc** [lucko/LuckPerms#27]
The build process fails during luckperms-common while trying to download zPermissions lib.

https://gist.github.com/bloodmc/dcbd8eb5a92f360b1f9cacc4859ffe47

**Comment by lucko** [comment]
Not an issue with the project afaik. I just cleared my local maven repo and the build ran fine.

I'm guessing it's more an issue with my nexus repository, although I'm not sure what the issue is. Googling "maven peer not authenticated" produces a few results. 

I do know that the project will not build if you're using any of the earlier Maven 3 releases. (at least I know the one that comes bundled with IntelliJ doesn't work). Perhaps that's causing this issue too?

So yeah uh, I'm not really sure. 😕
