### ISSUE TITLE
Vault - Chat#getPlayerInfoInteger - Returns always the default value

### ISSUE THREAD

**Issue by Sir-Will** [lucko/LuckPerms#270]
the method `Chat#getPlayerInfoInteger` from Vault does always return the default value with LuckPerms.

**Comment by lucko** [comment]
Can you show me the code you're using?

**Comment by Sir-Will** [comment]
`MyPlugin.getChat().getPlayerInfoInteger(player, "myplugin.daily", 0);`

**Comment by lucko** [comment]
Is `player` online?

**Comment by Sir-Will** [comment]
offline

**Comment by lucko** [comment]
You cannot use Vault for offline player lookups. Use the native API.

**Comment by Sir-Will** [comment]
So I need to use the API instead of using Vault to make the plugin useable for multiple permission plugins?

**Comment by lucko** [comment]
Yes, as I just said, you cannot use Vault for offline player lookups.

The Vault Permission API is not written in a way which allows for i/o in the background. When it was written, it was the norm that permission plugins would store all of their data in memory.

For offline players, I have to perform i/o in order to retrieve data. The majority of plugins which use Vault do so on the main thread (since the majority of permission plugins are not thread safe). Put those two things together and you have a problem.

I cannot block the main thread with i/o calls, or your server will pause for a few seconds every time a plugin performs a Vault operation.

**Comment by Sir-Will** [comment]
Actually I'm wrong, sorry. I'm using it while the player is online.
Few seconds after the player logged in.

**Comment by Sir-Will** [comment]
That's how I want to use it atm:
```

**Comment by Sir-Will** [comment]
Thanks, that fixed it.
