### ISSUE TITLE
LP 5.2.24 is failing upon startup

### ISSUE THREAD

**Issue by Vulant** [lucko/LuckPerms#2703]
### Description

I updated LP 5.2.3 to LP 5.2.24 in order to fix a string error: https://hastebin.com/aqixazibiy.apache

### Reproduction steps

1. Replace LP 5.2.3 with LP 5.2.24 and start up the server.

### Expected behaviour

Expected LP to not fail upon start up.

### Environment details

* Server type/version: SpongeForge 1.12.2
* LuckPerms version: LP 5.2.24

Startup Log: https://bytebin.lucko.me/1ubHLlFge8

### Any other relevant details

Dualspiral said: "Luck has used a snapshot of API 8 to compile against, and really shouldn't have done, because that class doesn't exist in API 7, and I think it's actually called ResourceKey in API 8, not CatalogKey."

Yes. CatalogKey doesn't exist in API 7, and the build of API 8 that's being used seems to be old to me. https://github.com/lucko/LuckPerms/commit/0ea0ce9d268dce264a5a58138dff978a86b45459 is the one that broke compatibility."

**Comment by dualspiral** [comment]
To clarify - when our event listener registration code scans the methods, [it sees this](https://github.com/lucko/LuckPerms/commit/0ea0ce9d268dce264a5a58138dff978a86b45459#diff-caf2fe5c0f0ac0c9e8c87e07cb43ba8387dca7086990fc59308a6c03f5dceb7dR103) and fails because `CatalogKey` does not exist in API 7, nor will it exist in API 8 (it's been renamed to `ResourceKey`.

My suspicion is that it's because you're compiling against an API 8 snapshot that is well out of date - the builds on `repo.spongepowered.org` are _very_ old but largely (but not wholly) compatible with API 7 and you've bumped up against that here.

If you wish to compile against the recent API 8 builds, you should get them from `https://repo-new.spongepowered.org/`, but be aware that there are large differences between 7 and 8 that you would then need to reconcile!

**Comment by lucko** [comment]
Thanks, should be all sorted.

LP primarily targets API 7, but we build against 8-SNAPSHOT to add support for `SubjectDataUpdateEvent` which was added (years ago actually..) at the start of 8's development cycle.

I know more recent API 8 changes aren't compatible, I'm holding off on that until it gains a bit more stability.
