### ISSUE TITLE
Problem with prefix

### ISSUE THREAD

**Issue by DIMC09** [lucko/LuckPerms#2729]
A few days ago I configured the plugin all okay, today I want to make new groups and the prefixes of the new groups do not work, they do not appear as such, any solution? I have a vault, I have the latest version of everything and I do not know what happens, in the console I do not get any error
![Captura](https://user-images.githubusercontent.com/36123635/99462439-768c7a00-2912-11eb-8bb1-fef9e4c5c76b.png)
![Captura1](https://user-images.githubusercontent.com/36123635/99462447-78eed400-2912-11eb-83c4-28ea0c65e31e.png)
on the page it is clearly seen that the prefix is as such but in the game it does not appear

I have tried in all the ways, changing the order of the track and the groups as such, duplicating an already configured group and changing the weight and prefix but it does not work

**Comment by underscore11code** [comment]
As displayed in your first screenshot, you are not inheriting a prefix. This likely means you haven't saved from the editor, or have entered the prefix into the editor incorrectly. 

If you can't figure it out, could you send a `/lp editor` link?

*There was zero need for you to redact your UUID. Since you're offline mode (Piracy bad.), the UUID is based off of your name.*

**Comment by Aberdeener** [comment]
What 11 said, and just to clear potential worries about sharing an `lp editor` link: it is 100% safe to share it publicly
