### ISSUE TITLE
[SEVERE] Server crashes every few minutes

### ISSUE THREAD

**Issue by KhrysAK47** [lucko/LuckPerms#2766]
### Description
Basically every few minutes, all the users from the server get the ''Timed out'' screen and it crashes with the LuckPerms log.

### Reproduction steps

1. Have LuckPerms v5.1.26 along with PaperSpigot 1.8.8
2. Wait a few minutes
3. See error

### Expected behaviour
Well, the server not to crash after a few minutes. 

### Environment details
PaperSpigot 1.8.8 + ViaVersion (Dev build)

* Server type/version: `ExampleSpigot` running version `1.12.2` build `???`
LuckPerms version: v5.1.26`

Crash error: https://pastebin.com/D9DqG1qE

**Comment by Fefo6644** [comment]
You are quite a number of builds behind, see if it still happens with the latest one https://luckperms.net/download

**Comment by Fefo6644** [comment]
Also, keep in mind that stack trace you pasted isn't necessarily an error. The crash log includes information from all threads running on the server, and since LuckPerms does most of its work asynchronously, you will probably see a lot of them. If anything, please provide the **entire** crash log and the whole server log as well (located in `logs/latest.log`) \:)

**Comment by lucko** [comment]
Nothing there to suggest LP is the cause of a crash
