### ISSUE TITLE
Seprating permissions between servers

### ISSUE THREAD

**Issue by GamingVexed** [lucko/LuckPerms#2780]
I use bungeecord on my server i use MySQL storage method, but i wanna seprate permissions on servers, on editor i made that /fly can be only done in survival on donor rank, but i dosen't allow to that in survival, i also changed config like this:

 The name of the server, used for server specific permissions.

 - When set to "global" this setting is effectively ignored.
 - In all other cases, the value here is added to all players in a "server" context.
 - See: https://github.com/lucko/LuckPerms/wiki/Context
server: Survival

**Comment by lucko** [comment]
Please don't disregard the issue template - it's there for a reason...

If you have an actual bug report, then please open another issue and fill it out correctly. Otherwise, the best place to aim any questions is our Discord server.

**Comment by GamingVexed** [comment]
Everyone ignores my issue on discord.

**Comment by Turbotailz** [comment]
So keep posting it.

But also doing what Luck said and creating an issue with the proper template will be very useful.

**Comment by Fefo6644** [comment]
> Everyone ignores my issue on discord.

People both on the Discord server and in here are not paid for support nor are there 24/7 to help; volunteers help because they *want* to help, but are not obligated to do so. You are completely free to re-post your issue; if you do it in here, **please** follow the issue template; if you do it in the Discord server maybe ask in #general-2 which is usually less crowded and wait patiently for a response.
