### ISSUE TITLE
LuckPerms permissions inconsistent across 3 different viewing mediums

### ISSUE THREAD

**Issue by Pugabyte** [lucko/LuckPerms#2783]
### Description

LuckPerms is showing 3 different permission sets:

**Yaml file**
![image](https://user-images.githubusercontent.com/12417961/102742144-37db4c80-4322-11eb-9c8b-1ae89547f0b3.png)

**Editor**
![image](https://user-images.githubusercontent.com/12417961/102742136-327e0200-4322-11eb-927c-d0be400ba25a.png)

**Command**
![image](https://user-images.githubusercontent.com/12417961/102742152-3ca00080-4322-11eb-9cb0-dfa97841d631.png)

I've run `/lp sync` but nothing changed. I'm confident that the storage type is truly YAML.

**Comment by Laarryy** [comment]
if you could provide a pastebin of the yaml file and an editor link instead of screenshots, we will be able to place the relation each has in context with the others. Thanks!

**Comment by Pugabyte** [comment]
Editor: https://luckperms.net/editor/fcHndu47IJ
Yaml file: https://paste.bnn.gg/operator.yml

**Comment by Laarryy** [comment]
Thanks, could you please send a screenshot of the output of `/lp info` as well as the rest of the information originally requested in the issue template? The reason it is requested is because it allows us to help you quickly, and so we do not have to ask again. If you cannot remember what was originally asked, 
![image](https://user-images.githubusercontent.com/58414982/102744120-491e5c00-4316-11eb-8fa1-da430566a0ae.png) is a screenshot of the prompts.

Thank you!

**Comment by Pugabyte** [comment]
![image](https://user-images.githubusercontent.com/12417961/102747057-8510eb80-432d-11eb-8734-1d918fd627fc.png)

**Comment by lucko** [comment]
I'm not really clear what the issue is? From your screenshots, it looks like everything is working properly.

The template is not optional, please don't ignore it. It makes it so much more painful for us to help you. If you'd still like our help, please open a new issue and fill out the template properly.
