### ISSUE TITLE
Breaks blocklogger on fabric

### ISSUE THREAD

**Issue by yitzy299** [lucko/LuckPerms#2814]
### Description
Causes watchdog crashes with blocklogger on fabric

### Reproduction steps
Start a fabric server with luckperms, fabric API and blocklogger.
Currently unsure of what exactly causes the crash, but I have so far had 4 of these crashes reported since users added luckperms to their servers

### Expected behaviour
Blocklogger does not behave in a way that a watchdog could occur, even if there is a storage slowdown. I believe this is a conflict with luckperms

### Environment details
Fabric loader v0.10.8,
Fabric API 0.28.3+

https://mcpaste.io/353236c524d38bf9
https://mcpaste.io/674045043f4ddb82
https://paste.dedimc.io/uvoxekeqaz.sql

----
Additional notes
----
- I am aware luckperms uses some form of database. As the stacktrace says, there is an issue executing SQLite `PreparedStatement`s.

**Comment by ElijahRus250** [comment]
Since I have removed luckperms from my server I have not had any crashes anymore

**Comment by lucko** [comment]
> I am aware luckperms uses some form of database. As the stacktrace says, there is an issue executing SQLite `PreparedStatement`s.

The stacktrace says *specifically* that the issue is from executing `tech.dttp.block.logger` PreparedStatements.

```
java.lang.Error: Watchdog
	at org.sqlite.core.NativeDB.step(Native Method)
	at org.sqlite.core.DB.execute(DB.java:849)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54)
	at tech.dttp.block.logger.save.sql.helper.InsertPSBuilder$InsertRunner.execute(InsertPSBuilder.java:93)
	at tech.dttp.block.logger.save.sql.DbConn.writeInteractions(DbConn.java:98)
	at net.minecraft.class_3225.handler$zje000$interactInject(class_3225.java:1524)
```

LuckPerms *can* use SQLite, but by default it actually uses a different type of database, H2, which it seems you are using.

```
[04:44:21] [Server thread/INFO]: Loading storage provider... [H2]
```

There's nothing here to indicate that the issue has anything to do with LuckPerms, I suggest you report it to the author of blocklogger instead :) 

> Since I have removed luckperms from my server I have not had any crashes anymore

It is possible that the crashes you are experiencing are different to the ones posted at the start of this issue, but since you haven't provided any I have no way to confirm.
