### ISSUE TITLE
Website error

### ISSUE THREAD

**Issue by kolia22871** [lucko/LuckPerms#2828]
Hello. Help with an error on the site, after entering / lp editor, I go through the site and write 
"LuckPerms
Web Permissions Editor

There was an error loading the data. Either the URL was copied wrong or the session has expired.

Please generate another editor session with / lp editor. "
Screenshot - https://imgur.com/a/k9NtILb

**Comment by Turbotailz** [comment]
This could be due to a variety of reasons:

- your browser has an extension blocking the connection to bytebin (where the data is stored and read from). Try using another browser or private browsing mode
- your computer could have an anti-virus preventing the connection to bytebin. Disable your antivirus or try and use another device (another PC or mobile) to load the page
- your internet connection (ISP) could be blocking the connection to bytebin. Try using another wifi network if possible or use your mobile data to load the page

Hopefully this helps. Nothing we can do about it unfortunately.

**Comment by Turbotailz** [comment]
@kolia22871 we just made a change to the website that may improve the issue, can you please try again and see if it works?

**Comment by kolia22871** [comment]
@Turbotailz just a second

**Comment by kolia22871** [comment]
@Turbotailz Doesn't work anyway

**Comment by Turbotailz** [comment]
Did you try any of the options I mentioned before?

**Comment by kolia22871** [comment]
@Turbotailz I'll try another internet right now

**Comment by kolia22871** [comment]
@Turbotailz I tried from my phone and from another internet

**Comment by Fefo6644** [comment]
Could you send an editor link?
What version of LP are you running?
