### ISSUE TITLE
Warning when a player logs in with the same IGN as another player but different UUID.

### ISSUE THREAD

**Issue by BrodyBeckwith** [lucko/LuckPerms#2850]
### Description

Recently came across a warning/error when a player logged in with the username "Imperial", if you don't know this IGN is actually tied to two different UUID's/Mojang accounts. This causes LuckPerms to throw a warning in console when they both login or when one logs in after the other. I'm unsure of what consequences this may have on luckperms 

### Reproduction steps

1. Get an account with the same IGN as another player.
2. Login both accounts to the server.

### Expected behaviour

I'm not sure to be honest, Because of the consequences of running LP commands on these players (how does it determine which one to run it for if not using UUID's) perhaps LuckPerms should not allow these accounts to join the server?

### Environment details

* Server type/version: `Latest Waterfall/Bungee`
* LuckPerms version: `4.4.31` (yikes i know its old)

https://gist.github.com/BrodyBeckwith/e55b9d0372cd5dad88eae23a9536052a

**Comment by BrainStone** [comment]
That old version is no longer supported.  
So unless you can recreate that issue on a modern LP version it’s pretty much mute.

**Comment by BrodyBeckwith** [comment]
> 
> 
> That old version is no longer supported.
> So unless you can recreate that issue on a modern LP version it’s pretty much mute.

I get same warning on 5.1.86 on one of our backend servers. I assume this would hold true for even the current version of LuckPerms as well. I see no commits which would of done anything about this?

**Comment by lucko** [comment]
You can either:

1) ignore the warnings
2) prevent those players from joining your server

I'm reluctant to remove the warnings - because well, they are warning you about a valid issue lol

Plugins simply are not going to behave correctly when two players are able to join the server using the same username. LuckPerms should be mostly ok, but bear in mind if you use their usernames to make changes using commands, it's probably going to actually apply the change to whichever user logged in most recently.
