### ISSUE TITLE
Group displayname colours no longer get formatted

### ISSUE THREAD

**Issue by WaitroseDev** [lucko/LuckPerms#2881]
### Description

After an update of LuckPerms from version 5.1.47 to 5.2.104, colours a no longer shown for the groups display name when running /lp listgroups
v5.1.47: https://i.imgur.com/oSfCPZw.png
v5.2.104: https://i.imgur.com/RvgKXCx.png

### Reproduction steps

Upgrade from any version 5.1.x to any version above v5.2.76 (These are the 2 I was running at the time)

### Expected behaviour

Expected displayname formatting to be shown

### Environment details

* Server type/version: `CraftBukkit` version `git-TacoSpigot-b1e9aab MC:1.8.8` - Proprietary fork of Spigot for our Network
* LuckPerms version: `v5.2.104`

**Comment by lucko** [comment]
Group display names (or think of them like aliases) are not meant to contain color codes.

The intention was to just allow nicer formatting (since LP forces the actual name to lowercase):
e.g. format `owner` --> `Owner` or `sradmin` --> `SeniorAdmin`.

Of course, there aren't any restrictions on what characters you can use - so you can put color codes in there if you want - but LP won't format them for you - at least in internal commands.

The reason for the change is because we phased out use of the legacy formatting code `&` in the internal LP messages, so the formatting no longer happens.
