### ISSUE TITLE
Strange crash with PlayerRoles

### ISSUE THREAD

**Issue by Niketats** [lucko/LuckPerms#2882]
LuckPerms Fabric v5.2.104
PlayerRoles 1.3.0
### Description
Crash with PlayerRoles

Log:
[2021-02-08-5.log](https://github.com/lucko/LuckPerms/files/5940160/2021-02-08-5.log)

**Comment by Laarryy** [comment]
For those who don't want to download random files: https://bytebin.lucko.me/fYAWUhS4gt 

Niketats, it looks like you're using two different mods that have the same purpose and they're conflicting. I'm not 100% sure on this due to my lack of experience with Fabric, but I believe you can only have one mod interacting/assigning permissions via the Fabric permissions API. LuckPerms and PlayerRoles both seem to do this, so you'll need to pick one.

**Comment by lucko** [comment]
The issue is with FabricProxy - not LuckPerms.

> User c8c1425f-75a9-3afb-a193-66d8112d1eee - NikitaCartes doesn't currently have data pre-loaded - denying login.

See #2873
