### ISSUE TITLE
Could not pass event PlayerLoginEvent to LuckPerms v5.2.118

### ISSUE THREAD

**Issue by SonSavasci** [lucko/LuckPerms#2915]
I have tried to fix my own but couldnt that than i came to your discord and they suggest someting but didnt solve here is my problem.

When i start my server than try to join it while server is opening (not quite opened yet) this errors comes to console

is it a big deal or not 

https://paste.insprill.net/iwofoyejaq.rb

**Comment by Fefo6644** [comment]
This is because `Player#getLocale()` didn't exist up until 1.12(.0), before that there used to be `Player.Spigot#getLocale()` but it was introduced in 1.8(.0) (something easily fixable tbh); there is no fix for this issue for the Bukkit Legacy build of LuckPerms other than just gracefully falling back to English.

**Comment by SonSavasci** [comment]
what should i do now couldnt understand. Maybe using another spigot ?

**Comment by Fefo6644** [comment]
If you want to 100% avoid the issue you can use an older version of LuckPerms for Spigot (before v5.2, you can find those in the resource page in spigotmc.org) but this issue can be taken care of with ease.
