### ISSUE TITLE
Prefix.0.rank not working

### ISSUE THREAD

**Issue by LaganDevs** [lucko/LuckPerms#2960]
when i use the `prefix.1000.[Rank]` in chat i just get:
![image](https://user-images.githubusercontent.com/80719974/112695753-d9060180-8e41-11eb-9fb9-a48c9144228a.png)

**Comment by benwoo1110** [comment]
the issue template just goes… poof. Please follow the issue template, it will help a lot in trying to debug your issue. Tho that being said, ensure you have vault and a chat plugin installed for prefix to work.

**Comment by Laarryy** [comment]
@LaganDevs these links may be useful, but the issue will be closed because you did not follow the carefully crafted template. 

In short, LuckPerms does not perform any chat formatting of its own. 
LuckPerms only acts as the source for prefixes / suffixes, it doesn't actually apply them. You need an appropriately configured chat/tablist formatting plugin for them to be displayed. If the values appear correctly when you run /lp user <user> info, LuckPerms is doing its job!

This will help with when your prefix isn't showing: https://luckperms.net/wiki/FAQ#why-are-prefixessuffixes-not-working

And it appears that you are using EssentialsX and perhaps EssentialsXChat which would display prefixes for you - if that's the case you should context EssentialsX support for help with it.
