### ISSUE TITLE
It is recommended to add a track function

### ISSUE THREAD

**Issue by 157946a** [lucko/LuckPerms#2962]
I personally recommend adding a time-limited track function, which has the same meaning as time-limited permissions and time-limited inheritance groups, that is, after the time is up, the track will automatically be downgraded by one level, and if not, the track will be automatically kicked out.

**Comment by Tavies** [comment]
Having the ability to write a promotion and a new time would make this amazing. You could have a promotion level (progression along the track) and a duration. So that way you could easily temp promote someone using the same command.

There would need to be a decision about making a marker for the player's base rank or just making a new track to use for this system.

Example:
Default->User->VIP->VIP+
/lp user tavies temppromote track1 1m

Using the command the first time would promote tavies to User for 1 month, using it a second time would promote to VIP for a new month. If at any time the timer goes to 0, then they get demoted back to default.

**Comment by lucko** [comment]
Hey, interesting idea!

I think for now I want to keep track promotions for permanent groups only. Of course, you can still add specific temporary groups using `parent addtemp` - or implement this functionality yourself using the API!

**Comment by Tavies** [comment]
Though not overly complicated, when using the parent addtemp, having to remove the temp before re-adding it to renew the time rather than it overwriting seems like an extra step (though I can see it making sense if the time is less). My thinking with the temppromote could simplify rank changes as well as upgrades using a single command.

**Comment by CuBeR116** [comment]
UP. I need this feature too

**Comment by xicxen** [comment]
Is it possible to have this feature implemented? I need something exactly like this and temp add will not work for what I am making.

Thanks!
