### ISSUE TITLE
MongoDB failing

### ISSUE THREAD

**Issue by CommandCracker8** [lucko/LuckPerms#2988]
I am getting a me.lucko.luckperms.lib.mongodb.MongoSocketException please help

**Comment by powercasgamer** [comment]
Can you upload your `logs/latest.log` file to a paste site like https://paste.lucko.me/? Also next time please follow the issue template, it's there for a reason.

**Comment by CommandCracker8** [comment]
OK, sorry. Here is the link: https://paste.lucko.me/wq9wUGhHhU

I reloaded several times

**Comment by powercasgamer** [comment]
A few things, don't reload your server just restart [read more here](https://matthewmiller.dev/blog/problem-with-reload/). Your host address is unknown, try using `quirkycraft.ygqma.mongodb.net` instead of `quirkycraft.ygqma.mongodb.net/luckperms`? If that doesn't work you'll want to contact your hosting for help with that.

**Comment by CommandCracker8** [comment]
I am using default mongodb hosting and I did try the other one

**Comment by lucko** [comment]
The field you are entering a URL into expects a hostname only.

i.e. just the `quirkycraft.ygqma.mongodb.net` bit
