### ISSUE TITLE
Warn users with multiple permissions plugins installed

### ISSUE THREAD

**Issue by codingJWilliams** [lucko/LuckPerms#3006]
### Description
In the case that LuckPerms detects a plugin such as PermissionsEx, PowerRanks, etc is installed on the server too, it would alert the server owner to this.

### Proposed behaviour
It could output in a few places depending on which would work best:

 * It could output into console on boot - although this might be missed by some users
 * It could output to console whenever a player joins
 * It could output whenever an OP'd player joins the game (can't check permissions for the alert, as obviously permissions will be fucked if multiple plugins are installed)
 * It could output at the bottom / top of every `/lp` command that is ran

**Comment by lucko** [comment]
The commit above adds a mesage to the console / log file every time a player connects and another permission plugin is detected.

Some permission plugins (those that conform strictly to the Bukkit PermissionAttachment API) actually will be compatible - it's just other plugins that inject using reflection like LP does which won't be. It makes sense to have a generic check there instead of a hardcoded list of other permission plugins to detect IMO.

Thanks for the suggestion! :)
