### ISSUE TITLE
Luckperms error on CraftBukkit Startup

### ISSUE THREAD

**Issue by RealFX-Code** [lucko/LuckPerms#3055]
### Description
I have the issue where I can't use luckperms with craftbukkit, I get the errors pasted in the pastebin.
https://pastebin.com/9zfgu2t2

### Reproduction steps
Luckperms does not make a config and does not start, I don't know why luckperms does this. I do not know how to reproduce this error, as I don't know why the error occurs.

### Expected behaviour
I expected luckperms to work normally like it did every time I set up a bukkit server.

### Environment details
Current LP version: LuckPerms v5.3.42 (CraftBukkit version)

Java Version:      java version "1.8.0_291"
                          Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
                          Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

### Screenshot

I have attached a screenshot of my console when LuckPerms tries to load.

![LP error](https://user-images.githubusercontent.com/25106569/120930737-d3088880-c6ee-11eb-8a6e-4aab00115146.png)

**Comment by lucko** [comment]
What server version / type are you using?

**Comment by RealFX-Code** [comment]
> What server version / type are you using?

i am using the latest 1.8.8 build of craftbukkit, straight from https://getbukkit.org/

**Comment by MackenzieMolloy** [comment]
Any specific reason you're using Bukkit over Spigot, or Paper?

**Comment by RealFX-Code** [comment]
> Any specific reason you're using Bukkit over Spigot, or Paper?

no, if it is bukkit's fault, i could just change it.

**Comment by X3n044** [comment]
Hello

ave same error, but papermc 1.17, luckperms 5.3.50, java version "16.0.1" 2021-04-20

`[06:53:55] [Server thread/ERROR]: Error occurred while enabling LuckPerms v5.3.50 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/lib/gson/JsonParseException
→   at me.lucko.luckperms.lib.adventure.text.serializer.gson.GsonComponentSerializerImpl$BuilderImpl.build(GsonComponentSerializerImpl.java:149) ~[?:?]
→   at me.lucko.luckperms.lib.adventure.text.serializer.craftbukkit.BukkitComponentSerializer.<clinit>(BukkitComponentSerializer.java:56) ~[?:?]
→   at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$Message.createMessage(BukkitFacet.java:67) ~[?:?]
→   at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitFacet$Message.createMessage(BukkitFacet.java:59) ~[?:?]
→   at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudience.createMessage(FacetAudience.java:361) ~[?:?]
→   at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudience.sendMessage(FacetAudience.java:157) ~[?:?]
→   at me.lucko.luckperms.lib.adventure.audience.ForwardingAudience.sendMessage(ForwardingAudience.java:65) ~[?:?]
→   at me.lucko.luckperms.lib.adventure.audience.Audience.sendMessage(Audience.java:207) ~[?:?]
→   at me.lucko.luckperms.lib.adventure.audience.Audience.sendMessage(Audience.java:183) ~[?:?]
→   at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:70) ~[?:?]
→   at me.lucko.luckperms.bukkit.BukkitSenderFactory.sendMessage(BukkitSenderFactory.java:42) ~[?:?]
→   at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:85) ~[?:?]
→   at me.lucko.luckperms.common.locale.Message$Args1.send(Message.java:4066) ~[?:?]
→   at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:119) ~[?:?]
→   at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
→   at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:51) ~[?:?]
→   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-79]
→   at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.jar:git-Paper-79]
→   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-79]
→   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-79]
→   at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.lib.gson.JsonParseException
→   at java.net.URLClassLoader.findClass(URLClassLoader.java:433) ~[?:?]
→   at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
→   at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
→   ... 25 more
[06:53:55] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.3.50
[06:53:55] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[06:53:55] [Server thread/ERROR]: Error occurred while disabling LuckPerms v5.3.50 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.lucko.luckperms.common.treeview.PermissionRegistry.close()" because "this.permissionRegistry" is null
→   at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:230) ~[?:?]
→   at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onDisable(LPBukkitBootstrap.java:191) ~[?:?]
→   at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onDisable(BukkitLoaderPlugin.java:56) ~[?:?]
→   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-79]
→   at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-79]
→   at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.jar:git-Paper-79]
→   at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-79]
→   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-79]
→   at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by lucko** [comment]
> Hello
> 
> Have the same error, but papermc 1.17 git 79, luckperms 5.3.50, java version "16.0.1" 2021-04-20
> 
> With luckperms 5.3.3 its ok.

@X3n044 That is not the same error - please try deleting the `/libs` directory then restarting.

**Comment by lucko** [comment]
re: this issue - I attempted a lazy fix (see above) but since reverted it because it was ugly and making checkstyle tests fail.

I don't really have the time to put more energy into this at the moment - sorry - I suggest you just update to Spigot or Paper, as that will fix the issue also.
