### ISSUE TITLE
Indicator in config file for /lp reloadconfig

### ISSUE THREAD

**Issue by AgentIce** [lucko/LuckPerms#3152]
Hello once again! xD
Today, we helped someone out in the discord, where the user had changed the server name in the config file and reloaded the config, hoping the server name change would work, allowing the user to use the context without a server restart. Generally speaking, I understand why server owners try to avoid performing server restarts. So here is my proposal:

It is nowhere to be found which settings exactly get reloaded and will work on /lp reloadconfig. So my idea is to add an indicator into the config file. Maybe symbols even, such as a checkmark for 'works on reloadconfig', an x for 'does not work with reloadconfig'. This way, we can all learn what gets applied on reloading the config file and what does not, being able to better assist users seeking help :3 
<3

**Comment by OmegaWeaponDev** [comment]
Not going to lie, All my time using and supporting users with Luckperms even I am not quite sure which settings are actually updated with the reloadconfig command as there is no where that actually states which settings they are. Even maybe having the list on the wiki, under the reload command might be a good idea if not wanting to update the config file with a visual representation.

**Comment by emilyy-dev** [comment]
I personally just go to the [`ConfigKeys` file](https://github.com/lucko/LuckPerms/blob/9cd33d26f276b255d065d17cf471c4db0b78f6ed/common/src/main/java/me/lucko/luckperms/common/config/ConfigKeys.java) and check whether or not the setting I'm interested in is `notReloadable` or not.. although I believe it's safe to assume only a handful of people actually go that far and I'm among the minority.

I think a good place for this information to live in would be the wiki. Given the amount of settings the plugin has (and the fact that not all of them make sense to exist in all platforms, but they are "present" (e.g. Vault settings in Fabric)) I think that in-game indicators (chat hover cards or messages) it will get quite bulky quite fast. Plus being in the wiki one could easily Ctrl + F the setting they're interested in, rather than staring at a long list for minutes to find it, maybe even skipping it a few times without noticing (although there could also be a command?).

**Comment by lucko** [comment]
Feel free to make a wiki PR :)
