### ISSUE TITLE
Converting from groupmanager to mysql. Error -> Could not parse UUID for user:

### ISSUE THREAD

**Issue by andrewkm** [lucko/LuckPerms#326]
I'm getting these errors when converting from groupmanager.
Command: /lp migration groupmanager false
This is happening for about 60% of users.

Result ends at:
https://pastebin.com/raw/LQzDbjDu

Using very latest LuckPerms from jenkins as of this issue post.

**Comment by lucko** [comment]
This is thrown when GroupManager's `User#getUUID` method returns a value which is not a UUID.

https://github.com/lucko/LuckPerms/blob/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/migration/MigrationGroupManager.java#L191

It's pretty clear that shouldn't be happening, but there's not much I can do about it. ;)

My guess is that, for whatever reason, GM is still storing player data using usernames. (this means that whenever these players change their username, they'd lose the data anyway). It might be that they simply haven't connected since you upgraded to a GM version with UUID support, or that it was converted, and the old data was left there too.

It might be worth checking:

a) if any of these users have connected to your server recently, (or rather, since you upgraded to a UUID compatible GM build)

b) if they have data attached to their uuid in addition to the entries stored alongside their username.
