### ISSUE TITLE
Bug with Essentials Spawn when using storage format: mysql

### ISSUE THREAD

**Issue by lowheartrate** [lucko/LuckPerms#329]
I had an issue on my server earlier today when trying to set a spawn per group so that the default group will go to a certain location when using _/spawn_ and all the other groups will go to another. When it wasn't working the storage type I was using was _mysql_ instead of the default format _H2_. I went about going through all the plugins trying to figure out why it was sending every group to the default location instead of the _setspawn_ I set for the certain group. 

After changing the storage format from _mysql_ back to the default _H2_ it started to work again so the proper groups would go to the proper _/spawn_ location. Not sure why it works with one storage format and not the other but that is what fixed it. Wanted to bring it here to bring it to the attention of someone so that if there is a flaw in the code somewhere or something else it could possibly be fixed.

Best regards,
Codi / lowheartrate

**Comment by cwkfr** [comment]
I'm using mysql and I don't have that problem. 

EssentialsX 2.0.1-b474
LuckPerms 3.1.53

**Comment by lowheartrate** [comment]
@cwkfr I am using [EssentialsX 2.0.1](https://hub.spigotmc.org/jenkins/job/spigot-essentials/) and LuckPerms 3.2.20

**Comment by lucko** [comment]
It would've been because the data was different on each storage type. That's it.

The Essentials spawn system works off primary groups. So, you either need to set those for each player, or change the calculation method to parents-by-weight, and setup group weightings.

https://github.com/lucko/LuckPerms/wiki/Configuration#primary-group-calculation
