### ISSUE TITLE
Wildcard support for server names

### ISSUE THREAD

**Issue by DefinitlyEvil** [lucko/LuckPerms#390]
if you have several servers in a type: 
```
survival-1
survival-2
creative-1
creative-2
```
you may wanna use `survival-*` and `creative-*` to support both server groups maybe? 

or you can create a new feature called server groups. I strongly recommend the server group way. 
then we can have server groups like: `survivals` and `creatives`

**Comment by lucko** [comment]
See my replies here (since they kinda relate to this):
https://github.com/lucko/LuckPerms/issues/255

Wildcard servers were previously allowed, however, they were removed as they were hurting performance. An alternative was added in the form of static contexts.

You should use static contexts, to add a "server-type" context for each of your servers, and then set that to "creative" or "survival". 

These static contexts are defined in the `contexts.json` file.

**Comment by DefinitlyEvil** [comment]
nice, it helped a lot! thanks!
