### ISSUE TITLE
[Question] Could explain more about set xxx false and unset?

### ISSUE THREAD

**Issue by 5igm** [lucko/LuckPerms#414]
Hello, after I read the wiki, I am still a little confused about the difference between "set xxx false" and "unset xxx". 
For example, could you explain more details about the difference between commands "/luckperms group admin permission set minecraft.command.ban false" and "/luckperms group admin permission unset minecraft.command.ban"?

**Comment by etskinner** [comment]
I'm not the dev, but here's my take: 'set false' explicitly denies that permission, while 'unset' is agnostic toward that permission. This is an important distinction, consider a user's inherited permissions:

- User Alice belongs to group Moderator
- Group Moderator has permission X
- User Alice has permission X set to false, so that she still belongs to moderator, minus one permission

If Alice instead had that permission 'unset', she would by default inherit permission X, which we don't want her to have. So 'unset' is kind of like 'pass-through' any inherited permissions, while 'set true/false' explicitly sets that permissions in that context.

**Comment by 5igm** [comment]
@etskinner Thank you very much! 👍
