### ISSUE TITLE
To Luck Perms vs other plugins add Ultra permissions

### ISSUE THREAD

**Issue by renzotom** [lucko/LuckPerms#440]
Can you add Ultra Permissions there please? I mean that plugin - https://www.spigotmc.org/resources/ultra-permissions.42678/

They have good GUI, can´t we have also one?

**Comment by lucko** [comment]
Already kinda answered on #439.

In-game GUIs are a really cumbersome way to edit permission data, which is why I don't really plan to add such a feature to LP.

However, as pointed out on the other ticket, there is a web editor which you can use.

Also, if you're looking for a way to find all possible permissions, you can use `/lp tree`.

I hadn't heard of UltraPermissions until now, but it seems like it relies on users adding configs to define permissions to the system. LuckPerms doesn't need this, as it can use permissions from the servers registry / it's own caches.
