### ISSUE TITLE
Dynmap permissions lookup fail?

### ISSUE THREAD

**Issue by Dockter** [lucko/LuckPerms#494]
Hello, using LP within Sponge EcoSystem, latest builds.

When I attempt to do /dynmap pause, I am tripping this internal check with Dynmap.  Verbose of permissions doesn't indicate any issues.  Thoughts?

https://github.com/webbukkit/DynmapCore/blob/master/src/main/java/org/dynmap/DynmapCore.java#L1566

**Comment by spannerman79** [comment]
What version MC/Forge?

**Comment by mikroskeem** [comment]
Doesn't Dynmap use [own permissions system](https://github.com/webbukkit/DynmapForge/tree/master/src/main/java/org/dynmap/forge/permissions) on Forge?

**Comment by Dockter** [comment]
Forge 1.12.2, build 2501.  2.6 version of Dynmap.  I am using a developer build of SpongeForge, on the 9/30/2017 commit.

**Comment by lucko** [comment]
I think this may be fixed by:

https://github.com/SpongePowered/SpongeForge/pull/1660

which implements Forge's `IPermissionHandler`, which is what Dynmap is using.:

https://github.com/webbukkit/DynmapForge/blob/master/src/main/java/org/dynmap/forge/DynmapPlugin.java#L358

Otherwise, it falls back to the custom Dynmap `PermissionProvider` class, which, by the looks of it, doesn't route through the Forge permissions system.

https://github.com/webbukkit/DynmapForge/blob/master/src/main/java/org/dynmap/forge/permissions/OpPermissions.java#L36

... and rather just checks if the player is OP.

**Comment by Dockter** [comment]
Luck,

Dynmap isn't using Forge's permissions system at all.  Its using a fallback internal permissions handler within itself.  That PR won't help this issue.

**Comment by lucko** [comment]
Ah my bad, it just uses the same name. :P
