### ISSUE TITLE
 [LuckPerms] [WARN] User 087b5e77-db7b-3350-8d42-2bc7413759c6 - WafflezPlayz doesn't have data pre-loaded. - denying login.

### ISSUE THREAD

**Issue by WafflezPlayz** [lucko/LuckPerms#545]
How do I fix  [LuckPerms] [WARN] User 087b5e77-db7b-3350-8d42-2bc7413759c6 - WafflezPlayz doesn't have data pre-loaded. - denying login. It gives me this message when I log in:

![capture](https://user-images.githubusercontent.com/33784102/32980797-1fc04434-cc65-11e7-91e1-23ca7df45f14.PNG)

**Comment by lucko** [comment]
Can you please set `debug-logins` to true in the LuckPerms config.yml, restart your server, then try to connect again, and send me a pastebin of your log file.

**Comment by WafflezPlayz** [comment]
I've turned on debug-logins, do you mean send you a pastebin of a log file that has been created or a pastebin of the console

**Comment by WafflezPlayz** [comment]
[Log](https://pastebin.com/J3rKN3CC)

**Comment by lucko** [comment]
You cannot use CraftBukkit with LuckPerms when running in offline mode, due to this issue:

https://hub.spigotmc.org/jira/browse/SPIGOT-3541

You have a few options:
1. Use Spigot or Paper instead of CraftBukkit
2. Enable online mode
3. Stop using LuckPerms

My suggestion is to move to Paper. You can simply replace the craftbukkit jar with the one provided here:
https://ci.destroystokyo.com/job/PaperSpigot/
