### ISSUE TITLE
Internal Exception: me.lucko.luckperms.api.User.getGroupNames

### ISSUE THREAD

**Issue by Noudux** [lucko/LuckPerms#555]
I have install the new version of LuckPerms 4.0.19. After the install I have create a new config file. Connected with the database. Everyrhing looks ok. When I'm log in via Bungeecord that's no problem. But when I went to join 1 of the other servers I'll take the next message. Then I will kick out of my server.

23.11 17:36:36 [Connect] User Noudux, IP 31.201.35.167 
23.11 17:36:36 [Multicraft] Noudux ran command Message of the Day 
23.11 17:36:36 [Disconnect] User Noudux has disconnected, reason: Internal Exception: java.lang.NoSuchMethodError: me.lucko.luckperms.api.User.getGroupNames()Ljava/util/List; 
23.11 17:36:36 [Server] INFO Noudux left the game

**Comment by lucko** [comment]
The issue as far as I know is caused by this plugin:
https://www.spigotmc.org/resources/tab-1-8-x-1-12-x.30854/

It depends on an old version of the LP API, and throws that error when trying to retrieve prefixes. Looks like it's since been removed from Spigot - and it's not open source, so there's not a whole lot I can do. :/

**Comment by lucko** [comment]
Your options therefore are:

1. Downgrade to a `3.x.x` LuckPerms build
2. Remove the TAB plugin
3. Ask the author of the tab plugin to update it to work with the newer versions of LuckPerms.
