### ISSUE TITLE
Smart setting for apply-bukkit-child-permissions

### ISSUE THREAD

**Issue by BrainStone** [lucko/LuckPerms#612]
This might be a strange request but could you just ignore the child permissions if they end in an asterisk? Like create a third option for `apply-bukkit-child-permissions` like `smart` or `ignore-wildcards` or `ignore-asterisks` and make that default

**Comment by lucko** [comment]
Why?

LuckPerms just re-implements the Bukkit behaviour for child permissions.

**Comment by BrainStone** [comment]
Because such child permissions clash with the wildcards of LuckPerms. While others like `plugin.admin` make sense.

**Comment by lucko** [comment]
Wildcards in child permissions are never resolved or expanded by LuckPerms, so only exact matches work.

Child permissions are considered before wildcards so they can take precedence over the internal LP resolution of wildcards.

I don't see that could ever cause a conflict though. The plugins own child rules are considered before the wildcards, since really wildcards are just child permissions defined by LP at check time.

**Comment by lucko** [comment]
Gonna close this - in short, I don't think the setting is necessary.
