### ISSUE TITLE
Plz add a gui system

### ISSUE THREAD

**Issue by JordanWax12** [lucko/LuckPerms#619]
Listin i love ur plugin but its very complicated if u make a gui like ultrapermissions it would be amazing plz man ill pay if i have to

**Comment by lucko** [comment]
I've thought about it before, but decided that an in-game GUI system is a bad solution.

This conclusion wasn't reached because of laziness or lack of willingness to add new stuff, but rather because it's a bad way to manage permissions. 

### Why? well...

* The input methods are really limited. The only way to enter custom text via a GUI is using signs, anvil GUIs or conversation handlers. I feel that none of these are particularly intuitive.

* GUIs in some cases actually slow down the process of making changes - they're bulky, and often require a lot of navigating to find the menu you want to use.

* You're limited to the interfaces already in the game, a 9x6 chest containing items. (not super useful!) You can only have a tiny amount of information contained within the GUI and visible at any one time. 

* Even with lores, you have to actually hover over each item to view it's attributes. Without hovering, all you see is a chest full of random items.

* Even when enlarged, chests only take up a tiny amount of space on the screen.

Also, LuckPerms is a fairly big plugin, and runs on 3 different platforms.

It would take probably hundreds of hours to implement the full command functionality within in-game menus. It would be pretty much impossible to implement this for the BungeeCord variant. Implementing the same system for Sponge would be really difficult.

And all of this, for as previously explained, very little benefit.

As you can see from the comparison charts on LP's Spigot page, despite boasting "easy management through a GUI", when boiled down, UltraPermissions is really very basic in terms of useful functionality for managing a servers permissions.

Also: a friendly reminder that **premium does not mean better**. I'd argue that there are plenty of free permissions plugin which have been around for years (LuckPerms aside) which still outperform some of the premium permission plugins available on Spigot. (zPerms, for example.)


### Ok but I hear you, managing permissions through commands isn't ideal

LuckPerms has a unique solution to this problem - a web editor.

You can use one of the editor commands...

* `/lp user <user> editor`
* `/lp group <group> editor`

... to open up a new editor session, and then make changes to permission data in a fully functional web interface.

I think most people would agree that this is **far** better than any interface you'd be able to design using Minecraft chests.

Thanks for the suggestion - but for the reasons stated above, in-game GUIs aren't something I'm going to be adding. :) However, there's of course no reason why you couldn't code them yourself using the LuckPermsAPI - or pay someone else to code them for you.

**Comment by JordanWax12** [comment]
but its to complicated

**Comment by smmmadden** [comment]
not everyone understands permissions, but if you are to limit what users can and cannot do, setting up a permission based server requires time and commitment.  

I guarantee you will not get it right the first time (and that's okay), it is one of those areas where you'll constantly be tweaking.  Once you spend time understanding the structure and what it does, it will get easier over time.  

This is my fourth permission plugin and they all provide similar features, but with LuckPerms, you get a lot more editing power than any of the others.  Read the wiki, try each of the commands on a test server.  If you get it great, if not - there are developers out there for hire than can help. :-)

**Comment by Andre601** [comment]
> @JordanWax12 
>
> but its to complicated

Everything looks complicated and confusing first, or was f.e. PermissionsEx easy at the beginning.
Every person has it's own perseption of what is "easy" and what not.
Maybe the GUI is easy for you or other players, but for other peoples it's not. The Web-Editor is in my opinion a good solution, to manage and edit permissions, without the need of typing commands ingame (except the commands to open/load the editor and save/apply the changes.)

Also the editor got a few changes in the past weeks, to have more options to set and edit permissions.
Again, most things are looking complicated at the beginning, but with time comes experience.

I used PEX in my past and first thought too, that LuckPerms was complicated (even when I had experience with the command-syntax from my time with PEX), but with the time I managed to learn and adapt to the new stuff and even started to enjoy making groups and set permissions.

Just take your time and if you have any questions, feel free to join the Support-Discord and ask them there.

**Comment by BrainStone** [comment]
I personally think it doesn’t get any easier than using the web editor. It’s essentially a GUI on steroids. In case you haven’t tried it yet, you should.

**Comment by JordanWax12** [comment]
ok listin i love it but the problem im having is changing the players name so like the group would be [Owner] &eBananaaShake i cant find a way to change the color of the user and add a space with the group prefix

**Comment by BrainStone** [comment]
You can click on a permission in the editor to edit it.

**Comment by AsVaidas** [comment]
Created the GUI of LuckPerms using the API
https://www.spigotmc.org/resources/luckperms-in-gui.53460/
