### ISSUE TITLE
[Feature Request] Let the default /lp message be configurable

### ISSUE THREAD

**Issue by GiansCode** [lucko/LuckPerms#638]
Hi there,

This is an expansion upon #628 and referencing [this](https://github.com/lucko/LuckPerms/blob/6602b23f091140e1677b1a2ef93983a969ba6de4/common/src/main/java/me/lucko/luckperms/common/commands/CommandManager.java#L155) line 

Firstly, I'm not sure why this message is hardcoded and not configurable. Nonetheless, I'm sure there is a valid reason. Though, regular players don't need to see this. The request is to just add a permission check before this and/or add this message to the locale.

Most people may not find this useful, but, everything on our server follows a theme, and we'd like to have this follow, plus, it's redundant information for players. Shouldn't be too hard to add

Cheers

**Comment by lucko** [comment]
Usage messages are not in the locale file because they do not need to be translated. The usages are the same for all commands, regardless of the translation.`/lp` is not a user facing command and is only used by server administrators, so I don't see a need for customisation.

You can configure the prefix at the top of the locale file if you want to make the plugin 'look custom' - whatever that means.

> plus, it's redundant information for players

I entirely disagree with that statement - the messages sent on these lines are essential for us to be able to see when helping users debug issues.

https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/commands/CommandManager.java#L155-L159
