### ISSUE TITLE
LuckPerms Spams Console with Errors

### ISSUE THREAD

**Issue by zachdoug24** [lucko/LuckPerms#647]
As stated, my console is spammed with duplicated errors of `[Server thread/INFO]: [LuckPerms] [WARN] An exception was thrown whilst calculating the context of subject luckperms.api6.SubjectProxy(ref=SubjectReference(collection=user, subject=6a212a25-258d-44e2-8871-07cf42395b12))` whenever I join.

https://gist.github.com/zachdoug24/c5cea059a10cdd2b9813b617a7de6171

**Comment by lucko** [comment]
The error is most likely caused by another plugin on your server.

I need to see the full forge log file to tell you which one it is - the one you gave doesn't show the actual exception.

https://github.com/lucko/LuckPerms/blob/master/common/src/main/java/me/lucko/luckperms/common/contexts/AbstractContextManager.java#L179

**Comment by zachdoug24** [comment]
https://transfer.sh/Nei0/fml-server-latest.log

**Comment by lucko** [comment]
GriefPrevention error:
https://paste.lucko.me/y7PGLQrugT

Make sure you're using the latest version.
