### ISSUE TITLE
Tab completion of aliases

### ISSUE THREAD

**Issue by Phoenix616** [lucko/LuckPerms#670]
When using an alias of a sub command it will not start to tab complete it. I realise that adding all possible aliases to the tab complete list would be a bit too much but I think it would be nice if aliases would start to show up when you typed at least one letter.

**Comment by lucko** [comment]
Aliases fall into two categories.

* Shortened versions of the real commands, e.g. `/lp u Luck p set test.node true`

It makes no sense to provide tab completions for these (for obvious reasons) - I assume these were the aliases you were referring to with "all possible" options

* Equivalent commands (either for backwards compatibility or convenience), e.g. `/lp player Luck setgroup admin`

I'm against adding tab completions for these mainly because it adds confusion - for this same reason, the aliases do not appear anywhere in the plugin documentation or in the help menus in-game.

It's confusing because most users won't know what these aliases do, and might be lead to believe they're completely different commands with differing behaviour.

The only reason some of the aliases are still there is solely because leaving them isn't a maintenance burden. They don't really get in the way - but are there for people stuck in their ways. I really don't want to encourage their usage - because in some cases, they don't even make sense.

Hopefully you see what I mean. :)
