### ISSUE TITLE
It is impossible to give OP

### ISSUE THREAD

**Issue by DarkFort** [lucko/LuckPerms#699]
When I give myself OP via the console, she is given, but she is absent.
Without plugin of LuckPerms OP is given and functions normally.

**Comment by Zimon4eR** [comment]
Why do you even try to give yourself OP when plugin tells you that it will not work?
Do `/lp user <username> permission set minecraft.command true` if you want access to minecraft default commands..

**Comment by DarkFort** [comment]
I have a privilege on the server with OP. But it is not issued because of the LP. The players enter the / whois NICK command and see that they do not have an OP and ask me why it does not exist. There should be at least an OP visibility

**Comment by lucko** [comment]
If you're running a Sponge server (idk, I'm just guessing as you didn't give any information in the issue) - a players OP status has no effect on permission checks.

On Bukkit, OP status is considered, however it is considered AFTER permissions. You can use the autoop permission/feature if you want to control OP status with LuckPerms.

Aside from that, I don't really know what the problem is? What are you asking for exactly?
