### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Cuinoh** [lucko/LuckPerms#705]
[net2ftp-1516572285.zip](https://github.com/lucko/LuckPerms/files/1650333/net2ftp-1516572285.zip)
That's my logs and below I'm attaching the sponge jar I'm using

[net2ftp-1516572473.zip](https://github.com/lucko/LuckPerms/files/1650334/net2ftp-1516572473.zip)

**Comment by mikroskeem** [comment]
Please use https://hasteb.in and don't upload logs as zip files.

**Comment by Cuinoh** [comment]
I was told to upload the logs in a zip file by luck

**Comment by mikroskeem** [comment]
Oic, sorry.

**Comment by spannerman79** [comment]
> I'm attaching the sponge jar I'm using

You shouldn't need to attach it, just point/mention it.  For example `https://repo.spongepowered.org/maven/org/spongepowered/spongeforge/1.10.2-2123-6.0.0-BETA-1902/spongeforge-1.10.2-2123-6.0.0-BETA-1902.jar` or stating `spongeforge-1.10.2-2123-6.0.0-BETA-1902.jar` is enough.

**Comment by lucko** [comment]
I really have no clue why this issue is occurring. The database is throwing errors when acting on the LP tables, which should have already been created.

Please can you try:

1. Stopping your server completely.
2. Clearing the contents of `/luckperms/`, `/mods/LuckPerms-Sponge-x.x.x.jar` and `/config/luckperms/`
3. Downloading the latest version of the plugin from [Jenkins](https://ci.lucko.me/job/LuckPerms/)
4. Then starting your server again

I was unable to reproduce the issue using the jar provided.

**Comment by Cuinoh** [comment]
i’ve done that but i’ll try again when i get home

**Comment by lucko** [comment]
Feel free to reopen this issue if it still doesn’t work after performing the steps detailed above.
