### ISSUE TITLE
How do I get the prefixes working(Nukkit)

### ISSUE THREAD

**Issue by Smartjer123** [lucko/LuckPerms#803]
I tried all of the plugins you said to use and some other ones and nothing works. Is there anyway to get it to work on Nukkit?

**Comment by lucko** [comment]
You need to find a chat formatting plugin that works for Nukkit.

**Comment by Smartjer123** [comment]
Have any idea of one because I couldn't find any.

**Comment by Smartjer123** [comment]
You  should implement a chat formatter plugin into at least the Nukkit version and have it disabled by default

**Comment by Smartjer123** [comment]
I didn't mean it like that but ok

**Comment by lucko** [comment]
My view has always been that chat formatting is out of scope for a permissions plugin.

You'll need to find a chat formatting plugin to format the chat. If one doesn't exist for Nukkit, then sorry but that's not my problem.

Nukkit support was added to LuckPerms because someone asked (nicely!) for me to do it - and because it was fairly straightforward to do, given the way the rest of LP is designed.

However, I do not run a Nukkit server, and have very little in common with the community there - as such at this point in time, I don't have any interest in writing more plugins for the Nukkit ecosystem.
