### ISSUE TITLE
Argument based do not work Sponge

### ISSUE THREAD

**Issue by meredithdoto** [lucko/LuckPerms#923]
I'm setting up advanced perms (Argument based) and I have consulted my issue with gbalint on discord. He said that I have to have `luckperms.user.promote` & `luckperms.user.promote.<track>.<rank>` & `luckperms.user.promote.modify.<others/self>` but even when I have `luckperms.user.promote.modify.others` I can promote myself to max rank in track.

There is my verbose https://luckperms.github.io/verbose/?C7TnRrOvl5 
There is console https://prnt.sc/j7yr0o

I noticed that editor don't last for ever.
![owner](https://user-images.githubusercontent.com/24488182/39097594-b3ee04ac-465e-11e8-9878-881cdf062fc8.png)
![admin](https://user-images.githubusercontent.com/24488182/39097593-b0f38862-465e-11e8-89a0-81e5ba8b5806.png)
![mod](https://user-images.githubusercontent.com/24488182/39097597-ba3433c2-465e-11e8-8c7c-4b612d59a0eb.png)
![vip](https://user-images.githubusercontent.com/24488182/39097599-bb4d1580-465e-11e8-92c5-c1e49aee9c57.png)
![default user](https://user-images.githubusercontent.com/24488182/39097601-be9f5dce-465e-11e8-9995-7c84a5baf27b.png)
![myself](https://user-images.githubusercontent.com/24488182/39097602-c13f01ce-465e-11e8-95ae-be1c73e7ff70.png)

I'm using Sponge LP v4.1.72

Edit: Version + Editor screens

**Comment by lucko** [comment]
The verbose link has expired :/

**Comment by meredithdoto** [comment]
My problem is that i should not be able to promote others or self to higher group than mod on staff track
`default -> vip -> mod -> admin -> owner` 
`luckperms.user.promote.staff.mod` should block my promote on higher ranks

I had to borrow login for another account to test if I can promote someone to higher rank than mod and I can. That's the security risk.  
https://luckperms.github.io/verbose/?PNy8hiQy0G

Why is `luckperms.user.promote.staff.admin` & `luckperms.user.promote.staff.owner` true ? I did not specify that and if I remove `luckperms.user.promote` than I can't promote as expected and I have `luckperms.user.promote.staff.admin` undefined

**Comment by lucko** [comment]
Firstly - thank you for the detailed description :) It's very appreciated.

> Why is luckperms.user.promote.staff.admin & luckperms.user.promote.staff.owner true ?

This happens because of the way Sponge permissions work.

When you grant `luckperms.user.promote` - you also grant `luckperms.user.promote.staff` and `luckperms.user.promote.staff.admin` and `luckperms.user.promote.staff.admin.something` and so on.

You can either disable this feature here (be aware that doing so may break other plugins which rely on this behaviour - not recommended):

https://github.com/lucko/LuckPerms/blob/d73543408ed306c457247901187424e1deb82718/sponge/src/main/resources/luckperms.conf#L399-L407

Or simply negate the `luckperms.user.promote.staff.admin` permission for your group.

And just to clarify, by "negate" - I mean setting the permission to false.

That's why you're experiencing issues - it's not a bug though. ;)
