### ISSUE TITLE
How to negative default group?

### ISSUE THREAD

**Issue by LapizSeller** [lucko/LuckPerms#982]
Sorry my english bad.
In my server, rank list like this: Member -> Vip -> MVP
i'm set default group by command:
/lp group default parent add member server=factions
So every player join this faction server start with member rank, when player buy vip rank, but they always has default group so they still in member group.
In this case player inherit all permissions from both Member and Vip group. 
How i can negative (remove Member group) when player change to Vip group? i tried to add permisson "group.member" by this command:
/lp group vip permission set group.member false
to Vip group but it's not negative member group.

**Comment by andrewkm** [comment]
Can you let us know “why” you don’t want them in default / member group afterwards?
This would help assisting you :)

If it is due to primary group, simply set VIP to be weighted higher.
If it is due to permissions, simply weight VIP higher and negate what you don’t want from default / member.

Optimally you would remove member and apply VIP, but seeing as you set default to inherit member, I recommend adjusting your weights.

You can as well use default assignments, to apply member to every default member that joins your server, however this takes away from storage optimizations as you are then saving every player.

If you can provide more informarion that would be great :)

**Comment by LapizSeller** [comment]
example: kit permission like  essentials.kits.member, if you don't want other group receive this member kit you need negative this permission on every group.
Or prefix, in this case make stack prefix more complicated
I hope has simple way to negative a whole group
example: just negative permission "group.member" so it negative All permissions + meta from member group.

**Comment by lucko** [comment]
Make sure VIP has a higher weight than member, then just negate (set to `false`) on VIP the permissions you don't want to be inherited.
